# Measuring & Classifying Exponence

**NOTES**:
1. Definitions are still a little ad-hoc but the intuition all works
2. Measures still need need to implemented

A typology of exponence derived in set-theoretic terms making use of setmorph tools

In [1]:
import pandas as pd
%load_ext autoreload
%autoreload 2
import setmorph as sm
import itertools

Data files:

In [2]:
zen_df = sm.read_paradigms("src/setmorph/testdata/sample-zen-out.csv")
ngkolmpu_df = sm.read_paradigms("src/setmorph/testdata/sample-ng-tense-out.csv")
nuer_df = sm.read_paradigms("src/setmorph/testdata/sample-nuer-out.csv")
arabic_df = sm.read_paradigms("src/setmorph/testdata/sample-ar-out.csv")
rus_df = sm.read_paradigms("src/setmorph/testdata/sample-rus-out.csv")
fr_df = sm.read_paradigms("src/setmorph/testdata/sample-fr-out.csv")
uniq_df = sm.read_paradigms("src/setmorph/testdata/unique_test.csv")

## Delta

Delta is some feature based description of the distribution of a formative, $a$. It is a complete statement describing the cells where $a$ occurs. The total set of deltas for a formative can be considered the maximal knowledge of a speaker about the meaning/distribution of that formative.

- let $a$ be some formative 
- let $x$ be some set of features
- let $y$ be some cell in $\mathrm{dist}(a)$ 
- let $z$ be some cell in $\mathrm{cell}(\lambda)$ 

We can then define $\delta_a$ as
- some set of feature-sets, $\{ x_1, x_2, ... x_n \}$, such that: 

$$
\forall x \in \delta_a, \exists y, z \ (x \subseteq y, z) \\
\forall y, \exists x  \in \delta_a \ (y \supseteq x ) \\
\forall z \supseteq x, \exists y \supseteq x \ (z = y) 
$$

Which means:
1. All sets of features in $\delta_a$ are subsets of at least a cell which is in the distribution of $a$.
2. All cells in the distribution of $a$ are represented by a subset $x$ in $\delta_a$
3. All cells that are supersets of an $x$ in $\delta_a$ are in the distribution of $a$

## Simple exponence

a formatve, $a$, is said to be a *simple exponent* iff:

$$
\exists |\delta_a| = 1 \\
|x \in \delta_a| = 1 
$$

In [3]:
fr_df

     lexeme      cell    form       tier  slot formative     celllist
0     aller   prs.1sg     v E  segmental     0         v   (1sg, prs)
1     aller   prs.1sg     v E  segmental     1         E   (1sg, prs)
2     aller   prs.2sg     v a  segmental     0         v   (2sg, prs)
3     aller   prs.2sg     v a  segmental     1         a   (2sg, prs)
4     aller   prs.3sg     v a  segmental     0         v   (3sg, prs)
...     ...       ...     ...        ...   ...       ...          ...
1320  touer       inf   t w E  segmental     2         w        (inf)
1321  touer       inf   t w E  segmental     3         E        (inf)
1322  touer  prs.ptcp  t w ɑ̃  segmental     0         t  (ptcp, prs)
1323  touer  prs.ptcp  t w ɑ̃  segmental     2         w  (ptcp, prs)
1324  touer  prs.ptcp  t w ɑ̃  segmental     4        ɑ̃  (ptcp, prs)

[1325 rows x 7 columns]

We start by computing all shortest descriptions once and for all:

In [4]:
shortest_descrs = sm.delta_lexicon(fr_df)
shortest_descrs

,lexeme,tier,slot,formative,minimal description,# of cells,dist_a
0,aller,segmental,0,al,"{(inf), (2pl, prs), (ptcp), (prs, 1pl), (pst)}",10,"{(inf), (2pl, prs), (pst, 1pl), (3sg, pst), (2..."
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 1pl), (fut, 3sg), (fut, 2sg), (fut, 3pl..."
2,aller,segmental,0,v,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}",4,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}"
3,aller,segmental,1,E,"{(inf), (2pl, prs), (3pl, pst), (1sg), (fut, 2...",7,"{(1sg, prs), (inf), (2pl, prs), (3pl, pst), (f..."
4,aller,segmental,1,a,"{(pst, 1pl), (3sg), (2pl, pst), (2sg)}",8,"{(pst, 1pl), (fut, 3sg), (2sg, pst), (fut, 2sg..."
...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(pst, 1pl)}",1,"{(pst, 1pl)}"
241,touer,segmental,4,t,"{(2pl, pst)}",1,"{(2pl, pst)}"
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}"
243,touer,segmental,4,ɔ̃,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}",3,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}"
244,touer,segmental,4,ʁ,"{(3pl, pst)}",1,"{(3pl, pst)}"

In [5]:
simple = sm.classify_simple(shortest_descrs)
simple

,lexeme,tier,slot,formative,minimal description,# of cells,dist_a,simple?
0,aller,segmental,0,al,"{(inf), (2pl, prs), (ptcp), (prs, 1pl), (pst)}",10,"{(inf), (2pl, prs), (pst, 1pl), (3sg, pst), (2...",no
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 1pl), (fut, 3sg), (fut, 2sg), (fut, 3pl...",yes
2,aller,segmental,0,v,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}",4,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}",no
3,aller,segmental,1,E,"{(inf), (2pl, prs), (3pl, pst), (1sg), (fut, 2...",7,"{(1sg, prs), (inf), (2pl, prs), (3pl, pst), (f...",no
4,aller,segmental,1,a,"{(pst, 1pl), (3sg), (2pl, pst), (2sg)}",8,"{(pst, 1pl), (fut, 3sg), (2sg, pst), (fut, 2sg...",no
...,...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(pst, 1pl)}",1,"{(pst, 1pl)}",yes
241,touer,segmental,4,t,"{(2pl, pst)}",1,"{(2pl, pst)}",yes
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}",yes
243,touer,segmental,4,ɔ̃,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}",3,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}",no
244,touer,segmental,4,ʁ,"{(3pl, pst)}",1,"{(3pl, pst)}",yes

### Syncretism

A formative $a$ is considered to be an example of syncretism iff:

$\neg\exists \delta_a : |\delta_a| = 1$

There does not exist a description of 'a', $\delta_a$, which has a cardinality of 1, i.e. one set of features.

In [6]:
dfsyn = sm.classify_syn(shortest_descrs)
dfsyn

,index,lexeme,tier,slot,formative,minimal description,# of cells,dist_a,# sets minimally required
0,0,aller,segmental,0,al,"{(inf), (2pl, prs), (ptcp), (prs, 1pl), (pst)}",10,"{(inf), (2pl, prs), (pst, 1pl), (3sg, pst), (2...",5
1,1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 1pl), (fut, 3sg), (fut, 2sg), (fut, 3pl...",1
2,2,aller,segmental,0,v,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}",4,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}",4
3,3,aller,segmental,1,E,"{(inf), (2pl, prs), (3pl, pst), (1sg), (fut, 2...",7,"{(1sg, prs), (inf), (2pl, prs), (3pl, pst), (f...",5
4,4,aller,segmental,1,a,"{(pst, 1pl), (3sg), (2pl, pst), (2sg)}",8,"{(pst, 1pl), (fut, 3sg), (2sg, pst), (fut, 2sg...",4
...,...,...,...,...,...,...,...,...,...
240,240,touer,segmental,4,m,"{(pst, 1pl)}",1,"{(pst, 1pl)}",1
241,241,touer,segmental,4,t,"{(2pl, pst)}",1,"{(2pl, pst)}",1
242,242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}",1
243,243,touer,segmental,4,ɔ̃,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}",3,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}",3
244,244,touer,segmental,4,ʁ,"{(3pl, pst)}",1,"{(3pl, pst)}",1

**Measurement**

- Number of cells
- Number of 'sets' in minimal description

To be implemented:
- TODO: Ratio of values over length of a dimension, i.e. 2 cases out of 12 total (harder to do given current implementation.

### Cumulative exponence

A formative $a$ is considered an example of cumulative exponence iff:

$\neg\exists \delta_a : \forall x \in \delta_a, |x| = 1$

There does not exists a $\delta_a$ such that for all sets of features in $\delta_a$ they have a cardinality of 1.

In [7]:
max_dimensions = fr_df["celllist"].fillna("").apply(len).max()
cumulation = sm.classify_cumulation(shortest_descrs, max_dimensions)
cumulation

,lexeme,tier,slot,formative,minimal description,# of cells,dist_a,cumulative cells,longest cumulation,% cells cumulative,% dimensions cumulation
0,aller,segmental,0,al,"{(inf), (2pl, prs), (ptcp), (prs, 1pl), (pst)}",10,"{(inf), (2pl, prs), (pst, 1pl), (3sg, pst), (2...","{(prs, 1pl), (2pl, prs)}",2,20.000000,100.0
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 1pl), (fut, 3sg), (fut, 2sg), (fut, 3pl...",{},0,0.000000,0.0
2,aller,segmental,0,v,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}",4,"{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}","{(1sg, prs), (3sg, prs), (2sg, prs), (3pl, prs)}",2,100.000000,100.0
3,aller,segmental,1,E,"{(inf), (2pl, prs), (3pl, pst), (1sg), (fut, 2...",7,"{(1sg, prs), (inf), (2pl, prs), (3pl, pst), (f...","{(2pl, prs), (fut, 2pl), (3pl, pst)}",2,42.857143,100.0
4,aller,segmental,1,a,"{(pst, 1pl), (3sg), (2pl, pst), (2sg)}",8,"{(pst, 1pl), (fut, 3sg), (2sg, pst), (fut, 2sg...","{(pst, 1pl), (2pl, pst)}",2,25.000000,100.0
...,...,...,...,...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(pst, 1pl)}",1,"{(pst, 1pl)}","{(pst, 1pl)}",2,100.000000,100.0
241,touer,segmental,4,t,"{(2pl, pst)}",1,"{(2pl, pst)}","{(2pl, pst)}",2,100.000000,100.0
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}",{},0,0.000000,0.0
243,touer,segmental,4,ɔ̃,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}",3,"{(prs, 1pl), (fut, 1pl), (fut, 3pl)}","{(prs, 1pl), (fut, 1pl), (fut, 3pl)}",2,100.000000,100.0
244,touer,segmental,4,ʁ,"{(3pl, pst)}",1,"{(3pl, pst)}","{(3pl, pst)}",2,100.000000,100.0

**Measurement**

- Longest cumulation: how many feature values get cumulated at most
- Longest cumulation / longest possible cumulation
- % cells cumulative - percentage of cells in dist(a) which must be described using cumulation (based on minimal descrition currently)
- % dimensions - length of longest cumulation / longest possible cumulation

## Unique exponence

For a given value, v:
There is only one formative for which its all its deltas must contain that value:

$\exists!a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) $

alternatively:

$| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | = 1$

There exists exactly one $a$ such that all the descriptions of $a$, there exists a set in that description that contains that value.

In [8]:
uniq = sm.classify_unique(shortest_descrs)
uniq

          lexeme value  slot formative
40        croire   1sg     4         E
41        croire   3sg     4         a
41        croire   2sg     4         a
48         cuire   inf     1         ʁ
50         cuire   1sg     3         E
51         cuire   3sg     3         a
51         cuire   2sg     3         a
59     engloutir   inf     1         ʁ
60     engloutir   1sg     2         E
61     engloutir   3sg     2         a
61     engloutir   2sg     2         a
68         finir   inf     1         ʁ
69         finir   1sg     2         E
70         finir   3sg     2         a
70         finir   2sg     2         a
77          haïr   inf     1         ʁ
78          haïr   1sg     2         E
79          haïr   3sg     2         a
79          haïr   2sg     2         a
85        lisser   inf     1         E
88        lisser   3sg     3         a
88        lisser   2sg     3         a
92        lisser  ptcp     4        ɑ̃
95        manger   inf     1         E
98        manger   3sg     3         a
98        manger   2sg     3         a
102       manger  ptcp     4        ɑ̃
133       partir   1sg     4         E
134       partir   3sg     4         a
134       partir   2sg     4         a
193  reconvoquer   inf     1         E
201  reconvoquer  ptcp     3        ɑ̃
204    sonoriser   inf     1         E
212    sonoriser  ptcp     3        ɑ̃
218       sortir   1sg     4         E
219       sortir   3sg     4         a
219       sortir   2sg     4         a
225     squeezer   inf     1         E
228     squeezer   3sg     3         a
228     squeezer   2sg     3         a
232     squeezer  ptcp     4        ɑ̃


### Verbose exponence

For a given value, v and some word $\omega$:

$$| \{  a \in \mathrm{wordform}(\omega): \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1$ \\
$$

In [83]:
ve = sm.classify_verbose(shortest_descrs)
ve[ve.lexeme == "lisser"]

,lexeme,cell,value,formatives,# formatives
249,lisser,"(fut, 2pl)",fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
251,lisser,"(fut, 1sg)",fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
253,lisser,"(fut, 3pl)",fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
255,lisser,"(fut, 2sg)",fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
257,lisser,"(fut, 3sg)",fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
259,lisser,"(fut, 1pl)",fut,"[(segmental, 1, Ø), (segmental, 2, ʁ), (segmen...",3
260,lisser,"(2pl, pst)",2pl,"[(segmental, 3, a), (segmental, 4, t)]",2
261,lisser,"(2pl, pst)",pst,"[(segmental, 3, a), (segmental, 4, t)]",2
266,lisser,"(3pl, pst)",3pl,"[(segmental, 1, E), (segmental, 2, ʁ)]",2
267,lisser,"(3pl, pst)",pst,"[(segmental, 1, E), (segmental, 2, ʁ)]",2
273,lisser,"(pst, 1pl)",1pl,"[(segmental, 3, a), (segmental, 4, m)]",2
274,lisser,"(pst, 1pl)",pst,"[(segmental, 3, a), (segmental, 4, m)]",2

TODO: This is missing the word itself, can be added by merging with the original df.

**Measurement:**
    
- '# of formatives': number of formatives expressing that valuein a given word

To be implemented / further processing of the above dataframe:
- We could also do an average of formatives expressing a given value
- Number of cells where it is expressed verbose

### Allomorphy

This one is most problematic - still needs tweaking how it fits into the typology, how to measure and define.

There is more than one formative which expresses a given value and these don't co-occur.

For a given value, $v$, we see allomorphy if:

$$
\exists a, b : \forall \delta_a, \delta_b, \exists x \in \delta \ ( v \in x $ )\\
\{\Sigma \in \mathrm{dist}(a)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(b)| v \in \Sigma\} $$

Alternatively:

$$
| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1 \\
\exists a_i,a_j : \{\Sigma \in \mathrm{dist}(a_i)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(a_j)| v \in \Sigma\} 
$$

1. The number of formatives which have $v$ in all their deltas is more than one
2. There exist at least two formative which do not only occur in the same set of cells which contain $v$

In [20]:
allo = sm.classify_allomorphy(ngkolmpu_df)
pd.DataFrame(allo)

,lexeme,value,# allomorphs,% of allomorphs to cells containing v,forms
0,TELL,rmt,6,200.000000,"[[(segmental, 0, s), (segmental, 1, w)], [(seg..."
1,TELL,ipfv,4,200.000000,"[[(segmental, 3, ə)], [(segmental, 0, s), (seg..."
2,TELL,rct,4,133.333333,"[[(segmental, 0, s), (segmental, 1, w)], [(seg..."
3,TELL,dur,4,80.000000,"[[(segmental, 0, s), (segmental, 1, w)], [(seg..."
4,TELL,fut,2,100.000000,"[[(segmental, 0, s), (segmental, 1, ər)], [(se..."
...,...,...,...,...,...
58,STAB,ipfv,6,300.000000,"[[(segmental, 4, ə)], [(segmental, 0, s)], [(s..."
59,STAB,rct,5,166.666667,"[[(segmental, 0, s)], [(segmental, 2, i)], [(s..."
60,STAB,dur,7,140.000000,"[[(segmental, 0, s)], [(segmental, 2, i)], [(s..."
61,STAB,fut,2,100.000000,"[[(segmental, 0, s), (segmental, 1, ə), (segme..."
62,STAB,pfv,4,100.000000,"[[(segmental, 0, s), (segmental, 1, ə)], [(seg..."

**Measurement**

- '# of allomorphs'
- '% of allowmorphs to cells containing v' - this can be greater than 100% under current implementation.

Examples:


| (a) SG|  | (b) SG |   | (c) SG |   | (d) SG |
|---|      |---|        |---|        |---|
|x|        | x  |       | x  |       | x  |
|y|        | xy |       | x  |       | x  |
|z|        |  y |       | xy |       | yz |

The current implementation treats the analysis of 'allomorphy of singular' as:

- (a): x, y, z
- (b): x, y
- (c): x, y
- (d): x, yz

Another implementation might consider the following:

- (a): x, y, z
- (b): x, xy, y
- (c): x, xy
- (d): x, yz

## Higher-order exceptionality

See Carroll (2022)