# Measuring & Classifying Exponence

**NOTES**:
1. Definitions are still a little ad-hoc but the intuition all works
2. Measures still need need to implemented

A typology of exponence derived in set-theoretic terms making use of setmorph tools

In [1]:
import setmorph as sm

Data files:

In [2]:
zen_df = sm.read_paradigms("src/setmorph/testdata/sample-zen-out.csv")
ngkolmpu_df = sm.read_paradigms("src/setmorph/testdata/sample-ng-tense-out.csv")
nuer_df = sm.read_paradigms("src/setmorph/testdata/sample-nuer-out.csv")
arabic_df = sm.read_paradigms("src/setmorph/testdata/sample-ar-out.csv")
rus_df = sm.read_paradigms("src/setmorph/testdata/sample-rus-out.csv")
fr_df = sm.read_paradigms("src/setmorph/testdata/sample-fr-out.csv")
uniq_df = sm.read_paradigms("src/setmorph/testdata/unique_test.csv")

In [3]:
fr_features = sm.read_features("src/setmorph/testdata/fr_features.csv")
ng_features = sm.read_features("src/setmorph/testdata/ng_features.csv")
ar_features = sm.read_features("src/setmorph/testdata/ar_features.csv")
nuer_features = sm.read_features("src/setmorph/testdata/nuer_features.csv")
rus_features = sm.read_features("src/setmorph/testdata/rus_features.csv")
zen_features = sm.read_features("src/setmorph/testdata/zen_features.csv")

WARNING:root:The feature `mood` has a single value `ind`. No exponents of `ind` will be possible.
WARNING:root:The feature `tense` has a single value `prs`. No exponents of `prs` will be possible.
WARNING:root:The feature `voice` has a single value `act`. No exponents of `act` will be possible.
WARNING:root:The feature `case` has a single value `nom`. No exponents of `nom` will be possible.

## Delta

Delta is some feature based description of the distribution of a formative, $a$. It is a complete statement describing the cells where $a$ occurs. The total set of deltas for a formative can be considered the maximal knowledge of a speaker about the meaning/distribution of that formative.

- let $a$ be some formative 
- let $x$ be some set of features
- let $y$ be some cell in $\mathrm{dist}(a)$ 
- let $z$ be some cell in $\mathrm{cell}(\lambda)$ 

We can then define $\delta_a$ as
- some set of feature-sets, $\{ x_1, x_2, ... x_n \}$, such that: 

$$
\forall x \in \delta_a, \exists y, z \ (x \subseteq y, z) \\
\forall y, \exists x  \in \delta_a \ (y \supseteq x ) \\
\forall z \supseteq x, \exists y \supseteq x \ (z = y) 
$$

Which means:
1. All sets of features in $\delta_a$ are subsets of at least a cell which is in the distribution of $a$.
2. All cells in the distribution of $a$ are represented by a subset $x$ in $\delta_a$
3. All cells that are supersets of an $x$ in $\delta_a$ are in the distribution of $a$

## Simple exponence

a formatve, $a$, is said to be a *simple exponent* iff:

$$
\exists |\delta_a| = 1 \\
|x \in \delta_a| = 1 
$$

In [4]:
fr_df

     lexeme      cell    form       tier  slot formative     celllist
0     aller   prs.1sg     v E  segmental     0         v   (prs, 1sg)
1     aller   prs.1sg     v E  segmental     1         E   (prs, 1sg)
2     aller   prs.2sg     v a  segmental     0         v   (prs, 2sg)
3     aller   prs.2sg     v a  segmental     1         a   (prs, 2sg)
4     aller   prs.3sg     v a  segmental     0         v   (prs, 3sg)
...     ...       ...     ...        ...   ...       ...          ...
1320  touer       inf   t w E  segmental     2         w        (inf)
1321  touer       inf   t w E  segmental     3         E        (inf)
1322  touer  prs.ptcp  t w ɑ̃  segmental     0         t  (prs, ptcp)
1323  touer  prs.ptcp  t w ɑ̃  segmental     2         w  (prs, ptcp)
1324  touer  prs.ptcp  t w ɑ̃  segmental     4        ɑ̃  (prs, ptcp)

[1325 rows x 7 columns]

We start by computing all exponents relations once and for all:

In [5]:
exponents = sm.find_exponents(fr_df, fr_features)
exponents

,lexeme,tier,slot,formative,exponence,# of cells,dist_a
0,aller,segmental,0,al,"{(prs, 2pl), (prs, 1pl), (pst)}",10,"{(pst, 3pl), (1pl, pst), (prs, 1pl), (inf), (p..."
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 3sg), (fut, 1sg), (fut, 2sg), (fut, 3pl..."
2,aller,segmental,0,v,"{(prs, 3pl), (prs, 1sg), (prs, 3sg), (prs, 2sg)}",4,"{(prs, 3sg), (prs, 3pl), (prs, 1sg), (prs, 2sg)}"
3,aller,segmental,1,E,"{(pst, 3pl), (inf), (1sg), (prs, 2pl), (fut, 2...",7,"{(pst, 3pl), (fut, 1sg), (inf), (prs, 2pl), (p..."
4,aller,segmental,1,a,"{(1pl, pst), (pst, 2pl), (3sg), (2sg)}",8,"{(fut, 3sg), (prs, 2sg), (1pl, pst), (prs, 3sg..."
...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(1pl, pst)}",1,"{(1pl, pst)}"
241,touer,segmental,4,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}"
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(prs, ptcp)}"
243,touer,segmental,4,ɔ̃,"{(prs, 1pl), (fut, 3pl), (fut, 1pl)}",3,"{(prs, 1pl), (fut, 3pl), (fut, 1pl)}"
244,touer,segmental,4,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}"

In [6]:
sm.count_elts(exponents, "exponence", "# values")
exponents[exponents["# values"]==1]

,lexeme,tier,slot,formative,exponence,# of cells,dist_a,# values
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 3sg), (fut, 1sg), (fut, 2sg), (fut, 3pl...",1
5,aller,segmental,2,m,"{(1pl, pst)}",1,"{(1pl, pst)}",1
6,aller,segmental,2,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}",1
7,aller,segmental,2,ɑ̃,{(ptcp)},1,"{(prs, ptcp)}",1
9,aller,segmental,2,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}",1
...,...,...,...,...,...,...,...,...
237,touer,segmental,2,ʁ,{(fut)},6,"{(fut, 3sg), (fut, 1sg), (fut, 2sg), (fut, 3pl...",1
240,touer,segmental,4,m,"{(1pl, pst)}",1,"{(1pl, pst)}",1
241,touer,segmental,4,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}",1
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(prs, ptcp)}",1
244,touer,segmental,4,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}",1

### Syncretism

A formative $a$ is considered to be an example of syncretism iff:

$\neg\exists \delta_a : |\delta_a| = 1$

There does not exist a description of 'a', $\delta_a$, which has a cardinality of 1, i.e. one set of features.

In [7]:
exponents[exponents["# values"] > 1]

,lexeme,tier,slot,formative,exponence,# of cells,dist_a,# values
0,aller,segmental,0,al,"{(prs, 2pl), (prs, 1pl), (pst)}",10,"{(pst, 3pl), (1pl, pst), (prs, 1pl), (inf), (p...",3
2,aller,segmental,0,v,"{(prs, 3pl), (prs, 1sg), (prs, 3sg), (prs, 2sg)}",4,"{(prs, 3sg), (prs, 3pl), (prs, 1sg), (prs, 2sg)}",4
3,aller,segmental,1,E,"{(pst, 3pl), (inf), (1sg), (prs, 2pl), (fut, 2...",7,"{(pst, 3pl), (fut, 1sg), (inf), (prs, 2pl), (p...",5
4,aller,segmental,1,a,"{(1pl, pst), (pst, 2pl), (3sg), (2sg)}",8,"{(fut, 3sg), (prs, 2sg), (1pl, pst), (prs, 3sg...",4
8,aller,segmental,2,ɔ̃,"{(prs, 1pl), (prs, 3pl), (fut, 3pl), (fut, 1pl)}",4,"{(prs, 1pl), (prs, 3pl), (fut, 3pl), (fut, 1pl)}",4
...,...,...,...,...,...,...,...,...
235,touer,segmental,1,u,"{(prs, 2sg), (prs, 3sg), (prs, 1sg), (fut), (p...",10,"{(fut, 3sg), (prs, 2sg), (fut, 1sg), (prs, 3sg...",5
236,touer,segmental,2,w,"{(prs, 2pl), (prs, 1pl), (pst)}",10,"{(pst, 3pl), (1pl, pst), (prs, 1pl), (inf), (p...",3
238,touer,segmental,3,E,"{(pst, 3pl), (fut, 1sg), (inf), (prs, 2pl), (p...",6,"{(pst, 3pl), (fut, 1sg), (inf), (prs, 2pl), (p...",6
239,touer,segmental,3,a,"{(fut, 3sg), (1pl, pst), (fut, 2sg), (pst, 2pl...",6,"{(fut, 3sg), (1pl, pst), (fut, 2sg), (pst, 2pl...",6
243,touer,segmental,4,ɔ̃,"{(prs, 1pl), (fut, 3pl), (fut, 1pl)}",3,"{(prs, 1pl), (fut, 3pl), (fut, 1pl)}",3

**Measurement**

- Number of cells
- Number of 'sets' in minimal description

To be implemented:
- TODO: Ratio of values over length of a dimension, i.e. 2 cases out of 12 total (harder to do given current implementation.

### Cumulative exponence

A formative $a$ is considered an example of cumulative exponence iff:

$\neg\exists \delta_a : \forall x \in \delta_a, |x| = 1$

There does not exists a $\delta_a$ such that for all sets of features in $\delta_a$ they have a cardinality of 1.

In [8]:
max_dimensions = fr_df["celllist"].fillna("").apply(len).max()
sm.classify_cumulation(exponents, max_dimensions)
exponents

,lexeme,tier,slot,formative,exponence,# of cells,dist_a,# values,cumulative cells,longest cumulation,% cells cumulative,% dimensions cumulation
0,aller,segmental,0,al,"{(prs, 2pl), (prs, 1pl), (pst)}",10,"{(pst, 3pl), (1pl, pst), (prs, 1pl), (inf), (p...",3,"{(prs, 2pl), (prs, 1pl)}",2,20.000000,100.0
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 3sg), (fut, 1sg), (fut, 2sg), (fut, 3pl...",1,{},0,0.000000,0.0
2,aller,segmental,0,v,"{(prs, 3pl), (prs, 1sg), (prs, 3sg), (prs, 2sg)}",4,"{(prs, 3sg), (prs, 3pl), (prs, 1sg), (prs, 2sg)}",4,"{(prs, 3sg), (prs, 3pl), (prs, 1sg), (prs, 2sg)}",2,100.000000,100.0
3,aller,segmental,1,E,"{(pst, 3pl), (inf), (1sg), (prs, 2pl), (fut, 2...",7,"{(pst, 3pl), (fut, 1sg), (inf), (prs, 2pl), (p...",5,"{(prs, 2pl), (fut, 2pl), (pst, 3pl)}",2,42.857143,100.0
4,aller,segmental,1,a,"{(1pl, pst), (pst, 2pl), (3sg), (2sg)}",8,"{(fut, 3sg), (prs, 2sg), (1pl, pst), (prs, 3sg...",4,"{(1pl, pst), (pst, 2pl)}",2,25.000000,100.0
...,...,...,...,...,...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(1pl, pst)}",1,"{(1pl, pst)}",1,"{(1pl, pst)}",2,100.000000,100.0
241,touer,segmental,4,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}",1,"{(pst, 2pl)}",2,100.000000,100.0
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(prs, ptcp)}",1,{},0,0.000000,0.0
243,touer,segmental,4,ɔ̃,"{(prs, 1pl), (fut, 3pl), (fut, 1pl)}",3,"{(prs, 1pl), (fut, 3pl), (fut, 1pl)}",3,"{(prs, 1pl), (fut, 3pl), (fut, 1pl)}",2,100.000000,100.0
244,touer,segmental,4,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}",1,"{(pst, 3pl)}",2,100.000000,100.0

**Measurement**

- Longest cumulation: how many feature values get cumulated at most
- Longest cumulation / longest possible cumulation
- % cells cumulative - percentage of cells in dist(a) which must be described using cumulation (based on minimal descrition currently)
- % dimensions - length of longest cumulation / longest possible cumulation

## Values table

We reorganize the information so that each row represents one exponential value in a single word, with a list of its formatives.

In [9]:
values_words = sm.values_per_word(fr_df, exponents)

In [10]:
values_words

,lexeme,value,form,cell,formative
0,aller,1pl,i ʁ ɔ̃,fut.1pl,"((segmental, 2, ɔ̃),)"
1,aller,fut,i ʁ ɔ̃,fut.1pl,"((segmental, 0, iʁ), (segmental, 2, ɔ̃))"
2,aller,1sg,i ʁ E,fut.1sg,"((segmental, 1, E),)"
3,aller,fut,i ʁ E,fut.1sg,"((segmental, 0, iʁ),)"
4,aller,2pl,i ʁ E,fut.2pl,"((segmental, 1, E),)"
...,...,...,...,...,...
696,touer,pst,t w a,pst.2sg,"((segmental, 2, w), (segmental, 3, a))"
697,touer,3pl,t w E ʁ,pst.3pl,"((segmental, 3, E), (segmental, 4, ʁ))"
698,touer,pst,t w E ʁ,pst.3pl,"((segmental, 2, w), (segmental, 3, E), (segmen..."
699,touer,3sg,t w a,pst.3sg,"((segmental, 3, a),)"
700,touer,pst,t w a,pst.3sg,"((segmental, 2, w), (segmental, 3, a))"

We also need a table where rows represent values (across words) and also give lists of formatives

In [11]:
values = sm.values_table(values_words)
values

,lexeme,value,formative,formatives_by_word
0,aller,1pl,"{(segmental, 2, m), (segmental, 2, ɔ̃), (segme...","{((segmental, 2, ɔ̃),), ((segmental, 1, a), (s..."
1,aller,1sg,"{(segmental, 0, v), (segmental, 1, E)}","{((segmental, 1, E),), ((segmental, 0, v), (se..."
2,aller,2pl,"{(segmental, 2, t), (segmental, 0, al), (segme...","{((segmental, 1, E),), ((segmental, 1, a), (se..."
3,aller,2sg,"{(segmental, 0, v), (segmental, 1, a)}","{((segmental, 0, v), (segmental, 1, a)), ((seg..."
4,aller,3pl,"{(segmental, 2, ʁ), (segmental, 0, v), (segmen...","{((segmental, 1, E), (segmental, 2, ʁ)), ((seg..."
...,...,...,...,...
237,touer,fut,"{(segmental, 3, a), (segmental, 4, ɔ̃), (segme...","{((segmental, 1, u), (segmental, 2, ʁ), (segme..."
238,touer,inf,"{(segmental, 3, E)}","{((segmental, 3, E),)}"
239,touer,prs,"{(segmental, 2, w), (segmental, 3, E), (segmen...","{((segmental, 2, w), (segmental, 4, ɔ̃)), ((se..."
240,touer,pst,"{(segmental, 3, a), (segmental, 4, m), (segmen...","{((segmental, 2, w), (segmental, 3, E), (segme..."
241,touer,ptcp,"{(segmental, 4, ɑ̃)}","{((segmental, 4, ɑ̃),)}"

## Unique exponence

For a given value, v:
There is only one formative for which its all its deltas must contain that value:

$\exists!a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) $

alternatively:

$| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | = 1$

There exists exactly one $a$ such that all the descriptions of $a$, there exists a set in that description that contains that value.

In other words, given a lexeme and a value, only a single exponent expresses it.

In [12]:
sm.count_elts(values,"formative", "# formatives")
values[values["# formatives"] == 1]

,lexeme,value,formative,formatives_by_word,# formatives
7,aller,inf,"{(segmental, 1, E)}","{((segmental, 1, E),)}",1
10,aller,ptcp,"{(segmental, 2, ɑ̃)}","{((segmental, 2, ɑ̃),)}",1
34,croire,1sg,"{(segmental, 4, E)}","{((segmental, 4, E),)}",1
36,croire,2sg,"{(segmental, 4, a)}","{((segmental, 4, a),)}",1
38,croire,3sg,"{(segmental, 4, a)}","{((segmental, 4, a),)}",1
45,cuire,1sg,"{(segmental, 3, E)}","{((segmental, 3, E),)}",1
47,cuire,2sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
49,cuire,3sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
51,cuire,inf,"{(segmental, 1, ʁ)}","{((segmental, 1, ʁ),)}",1
56,engloutir,1sg,"{(segmental, 2, E)}","{((segmental, 2, E),)}",1
58,engloutir,2sg,"{(segmental, 2, a)}","{((segmental, 2, a),)}",1
60,engloutir,3sg,"{(segmental, 2, a)}","{((segmental, 2, a),)}",1
62,engloutir,inf,"{(segmental, 1, ʁ)}","{((segmental, 1, ʁ),)}",1
67,finir,1sg,"{(segmental, 2, E)}","{((segmental, 2, E),)}",1
69,finir,2sg,"{(segmental, 2, a)}","{((segmental, 2, a),)}",1
71,finir,3sg,"{(segmental, 2, a)}","{((segmental, 2, a),)}",1
73,finir,inf,"{(segmental, 1, ʁ)}","{((segmental, 1, ʁ),)}",1
78,haïr,1sg,"{(segmental, 2, E)}","{((segmental, 2, E),)}",1
80,haïr,2sg,"{(segmental, 2, a)}","{((segmental, 2, a),)}",1
82,haïr,3sg,"{(segmental, 2, a)}","{((segmental, 2, a),)}",1
84,haïr,inf,"{(segmental, 1, ʁ)}","{((segmental, 1, ʁ),)}",1
91,lisser,2sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
93,lisser,3sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
95,lisser,inf,"{(segmental, 1, E)}","{((segmental, 1, E),)}",1
98,lisser,ptcp,"{(segmental, 4, ɑ̃)}","{((segmental, 4, ɑ̃),)}",1
102,manger,2sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
104,manger,3sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
106,manger,inf,"{(segmental, 1, E)}","{((segmental, 1, E),)}",1
109,manger,ptcp,"{(segmental, 4, ɑ̃)}","{((segmental, 4, ɑ̃),)}",1
131,mourir,ptcp,"{(segmental, 5, ɑ̃)}","{((segmental, 5, ɑ̃),)}",1
133,partir,1sg,"{(segmental, 4, E)}","{((segmental, 4, E),)}",1
135,partir,2sg,"{(segmental, 4, a)}","{((segmental, 4, a),)}",1
137,partir,3sg,"{(segmental, 4, a)}","{((segmental, 4, a),)}",1
142,partir,ptcp,"{(segmental, 4, ɑ̃)}","{((segmental, 4, ɑ̃),)}",1
161,peler,inf,"{(segmental, 3, E)}","{((segmental, 3, E),)}",1
164,peler,ptcp,"{(segmental, 6, ɑ̃)}","{((segmental, 6, ɑ̃),)}",1
175,pouvoir,ptcp,"{(segmental, 6, ɑ̃)}","{((segmental, 6, ɑ̃),)}",1
186,recevoir,ptcp,"{(segmental, 6, ɑ̃)}","{((segmental, 6, ɑ̃),)}",1
194,reconvoquer,inf,"{(segmental, 1, E)}","{((segmental, 1, E),)}",1
197,reconvoquer,ptcp,"{(segmental, 3, ɑ̃)}","{((segmental, 3, ɑ̃),)}",1
205,sonoriser,inf,"{(segmental, 1, E)}","{((segmental, 1, E),)}",1
208,sonoriser,ptcp,"{(segmental, 3, ɑ̃)}","{((segmental, 3, ɑ̃),)}",1
210,sortir,1sg,"{(segmental, 4, E)}","{((segmental, 4, E),)}",1
212,sortir,2sg,"{(segmental, 4, a)}","{((segmental, 4, a),)}",1
214,sortir,3sg,"{(segmental, 4, a)}","{((segmental, 4, a),)}",1
219,sortir,ptcp,"{(segmental, 4, ɑ̃)}","{((segmental, 4, ɑ̃),)}",1
223,squeezer,2sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
225,squeezer,3sg,"{(segmental, 3, a)}","{((segmental, 3, a),)}",1
227,squeezer,inf,"{(segmental, 1, E)}","{((segmental, 1, E),)}",1
230,squeezer,ptcp,"{(segmental, 4, ɑ̃)}","{((segmental, 4, ɑ̃),)}",1
238,touer,inf,"{(segmental, 3, E)}","{((segmental, 3, E),)}",1
241,touer,ptcp,"{(segmental, 4, ɑ̃)}","{((segmental, 4, ɑ̃),)}",1

### Verbose exponence

For a given value, v and some word $\omega$:

$$| \{  a \in \mathrm{wordform}(\omega): \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1$ \\
$$

In [13]:
sm.count_formatives(values_words,"formative", "# formatives")
values_words[values_words.lexeme == "lisser"]

AttributeError: module 'setmorph' has no attribute 'count_formatives'

**Measurement:**
    
- '# of formatives': number of formatives expressing that valuein a given word

To be implemented / further processing of the above dataframe:
- We could also do an average of formatives expressing a given value
- Number of cells where it is expressed verbose

### Allomorphy

There is more than one formative which expresses a given value and these don't co-occur.

For a given value, $v$, we see allomorphy if:

$$
\exists a, b : \forall \delta_a, \delta_b, \exists x \in \delta \ ( v \in x $ )\\
\{\Sigma \in \mathrm{dist}(a)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(b)| v \in \Sigma\} $$

- There are two sets of formatives which both have v in some $x$ in their exponent set
- They occur in distinct words

$$
| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1 \\
\exists a_i,a_j : \{\Sigma \in \mathrm{dist}(a_i)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(a_j)| v \in \Sigma\} 
$$

1. The number of formatives which have $v$ in all their deltas is more than one
2. There exist at least two formative which do not only occur in the same set of cells which contain $v$

In [ ]:
sm.classify_allomorphy(fr_df, values)
values