A typology of exponence derived in set-theoretic terms making use of setmorph tools

In [1]:
%load_ext autoreload
%reload_ext autoreload

In [2]:
import setmorph as sm

Data files:

In [3]:
zen_df = sm.read_paradigms("src/setmorph/testdata/sample-zen-out.csv")
ngkolmpu_df = sm.read_paradigms("src/setmorph/testdata/sample-ng-out.csv")
nuer_df = sm.read_paradigms("src/setmorph/testdata/sample-nuer-out.csv")
arabic_df = sm.read_paradigms("src/setmorph/testdata/sample-ar-out.csv")
rus_df = sm.read_paradigms("src/setmorph/testdata/sample-rus-out.csv")
fr_df = sm.read_paradigms("src/setmorph/testdata/sample-fr-out.csv")
uniq_df = sm.read_paradigms("src/setmorph/testdata/unique_test.csv")

In [4]:
fr_features = sm.read_features("src/setmorph/testdata/fr_features.csv")
ng_features = sm.read_features("src/setmorph/testdata/ng_features.csv")
ar_features = sm.read_features("src/setmorph/testdata/ar_features.csv")
nuer_features = sm.read_features("src/setmorph/testdata/nuer_features.csv")
rus_features = sm.read_features("src/setmorph/testdata/rus_features.csv")
zen_features = sm.read_features("src/setmorph/testdata/zen_features.csv")

WARNING:root:The feature `mood` has a single value `ind`. No exponents of `ind` will be possible.
WARNING:root:The feature `tense` has a single value `prs`. No exponents of `prs` will be possible.
WARNING:root:The feature `voice` has a single value `act`. No exponents of `act` will be possible.
WARNING:root:The feature `case` has a single value `nom`. No exponents of `nom` will be possible.

*Note: all of this is also defined in the overleaf doc*

## Delta

Delta is some feature based description of the distribution of a formative, $a$. It is a complete statement describing the cells where $a$ occurs. It is a complete, restricted and non-redundant statement describing the cells where \(a\) occurs. The total set of deltas for a formative can be considered the maximal knowledge of a speaker about the meaning/distribution of that formative.

A valid **description** $\delta_a$ of a distribution, $\mathrm{dist}(a)$, is any set satisfying the following properties (there might be multiple):

1.  **Derived from the distribution**: $\delta_a$ contains only
    feature-value sets which are subsets of cells in $\mathrm{dist}(a)$:

    $$\forall x \in \delta_a, \exists y \in \mathrm{dist}(a), x \subseteq y$$

2.  **Complete**: Everything in the distribution is described

    $$\forall y \in \mathrm{dist}(a), \exists x  \in \delta_a \ (y \supseteq x )$$

3.  **Restricted**: Only cells in the distribution are described

    $$\forall x \in \delta_a, \forall z \in \mathrm{cells}, (z \supseteq x) \rightarrow (z \in \mathrm{dist}(a))$$

4.  **Non-redundant**: None of the $x$, $y$ in $\delta_a$ are subsets of
    each other.

    $$\forall x \in \delta_a, \not \exists y \in \delta_a, x \supseteq y$$

## Exponence


A formative is the exponent a set of set of values. Yet, having defined delta is still not sufficient to determine what values are properly *expressed* by *a*. We now define **exponence** as a descriptive, minimal, and informative set of valid descriptions.

.  $a$ is the **exponent** of a (unique) set of feature-value combinations which satisfies the following properties:

1.  **Descriptive**: All $x$ in $\text{exp}(a)$ are in at least one
    $\delta_a$: $$\exists \delta_a, x_i \in \delta_a$$

2.  **Minimal**: All $x$ in $\text{exp}(a)$ are equal to or subsets of
    at least one set of features in each $\delta_a$:
    $$\forall \delta_a, \exists y \in \delta_a, x_i \subseteq y$$

3.  **Informative**: For a given feature (dimension), the total sets of
    its possible values can not be in $\text{exp}$:
    $$\forall f,  \text{values(f)} \not \subseteq \text{exp}(a)$$

An empty exponence set means that the formative is part of a stem -- it fills *all* dimensions since it is always present.

## Values and their realizations


The exponence set is structured: it contains sets of combinations of values, such as **prs.ind**. Yet there is a relation between those inner values and the formatives:

The (partial) **realization** of a value $v$ is the set of all the formatives $a$ for which $v$ is in any element of $\textrm{exp}(a)$:

$$\text{real}(v) = \{ a |  \exists x \in \mathrm{exp}(a), v \in x \}$$

This function maps values to sets of formatives.

Symmetrically, the values expressed (even partially) by a formative are the union of all $x$ in $\text{exp}(f)$:

$$\text{vals}(f) = \cup_{x \in \text{exp}(f)} x$$

This function maps formatives to sets of values.

To start with, we thus need to compute *dist*, *exp*, *vals* for each formative:

In [5]:
fr_df

     lexeme         cell    form       tier  slot formative
0     aller   (prs, 1sg)     v E  segmental     0         v
1     aller   (prs, 1sg)     v E  segmental     1         E
2     aller   (prs, 2sg)     v a  segmental     0         v
3     aller   (prs, 2sg)     v a  segmental     1         a
4     aller   (prs, 3sg)     v a  segmental     0         v
...     ...          ...     ...        ...   ...       ...
1320  touer        (inf)   t w E  segmental     2         w
1321  touer        (inf)   t w E  segmental     3         E
1322  touer  (prs, ptcp)  t w ɑ̃  segmental     0         t
1323  touer  (prs, ptcp)  t w ɑ̃  segmental     2         w
1324  touer  (prs, ptcp)  t w ɑ̃  segmental     4        ɑ̃

[1325 rows x 6 columns]

In [6]:
exponents = sm.get_exponents(fr_df, fr_features)
exponents

,lexeme,tier,slot,formative,dist,exponence,vals,|vals|,|exp|
0,aller,segmental,0,al,"{(prs, ptcp), (prs, 2pl), (pst, 1sg), (pst, 1p...","{(pst), (prs, 1pl), (prs, 2pl)}","{pst, 2pl, 1pl, prs}",4,3
1,aller,segmental,0,iʁ,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
2,aller,segmental,0,v,"{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}","{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}","{2sg, 3pl, 3sg, 1sg, prs}",5,4
3,aller,segmental,1,E,"{(1sg, fut), (2pl, fut), (prs, 1sg), (pst, 1sg...","{(2pl, fut), (1sg), (inf), (pst, 3pl), (prs, 2...","{fut, 3pl, pst, 1sg, prs, 2pl, inf}",7,5
4,aller,segmental,1,a,"{(prs, 3sg), (3sg, fut), (pst, 1pl), (pst, 3sg...","{(3sg), (pst, 1pl), (pst, 2pl), (2sg)}","{2sg, 1pl, 3sg, pst, 2pl}",5,4
...,...,...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(pst, 1pl)}","{(pst, 1pl)}","{pst, 1pl}",2,1
241,touer,segmental,4,t,"{(pst, 2pl)}","{(pst, 2pl)}","{pst, 2pl}",2,1
242,touer,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
243,touer,segmental,4,ɔ̃,"{(fut, 1pl), (3pl, fut), (prs, 1pl)}","{(fut, 1pl), (3pl, fut), (prs, 1pl)}","{prs, 3pl, fut, 1pl}",4,3
244,touer,segmental,4,ʁ,"{(pst, 3pl)}","{(pst, 3pl)}","{pst, 3pl}",2,1

We also compute a table for the *real* function (this is calculated for each paradigm and value expressed in the paradigm):

In [7]:
reals = sm.get_reals(exponents)
reals

                                                               real  |real|
vals lexeme
1pl  aller        ((segmental, 2, m), (segmental, 1, a), (segmen...       4
     apprendre    ((segmental, 3, n), (segmental, 4, m), (segmen...       4
     boire        ((segmental, 4, m), (segmental, 4, ɔ̃), (segme...       4
     croire       ((segmental, 4, ɔ̃), (segmental, 3, j), (segme...       3
     cuire        ((segmental, 1, z), (segmental, 3, m), (segmen...       3
...                                                             ...     ...
ptcp reconvoquer                               ((segmental, 3, ɑ̃))       1
     sonoriser                                 ((segmental, 3, ɑ̃))       1
     sortir                                    ((segmental, 4, ɑ̃))       1
     squeezer                                  ((segmental, 4, ɑ̃))       1
     touer                                     ((segmental, 4, ɑ̃))       1

[242 rows x 2 columns]

Some of the measures also require a table which associates each value in a word to its realizations.

In [8]:
real_w = sm.get_real_per_word(fr_df, reals)

In [9]:
real_w

,lexeme,form,cell,wordform,vals,real_w,|real_w|
3,aller,a l a m,"(pst, 1pl)","((segmental, 2, m), (segmental, 1, a), (segmen...",1pl,"((segmental, 2, m), (segmental, 0, al), (segme...",3
9,aller,i ʁ ɔ̃,"(fut, 1pl)","((segmental, 2, ɔ̃), (segmental, 0, iʁ))",1pl,"((segmental, 2, ɔ̃))",1
15,aller,a l ɔ̃,"(prs, 1pl)","((segmental, 2, ɔ̃), (segmental, 0, al))",1pl,"((segmental, 2, ɔ̃), (segmental, 0, al))",2
23,apprendre,a p ʁ i m,"(pst, 1pl)","((segmental, 1, i), (segmental, 0, apʁ), (segm...",1pl,"((segmental, 4, m))",1
29,apprendre,a p ʁ ɑ̃ d ʁ ɔ̃,"(fut, 1pl)","((segmental, 0, apʁ), (segmental, 3, ʁ), (segm...",1pl,"((segmental, 4, ɔ̃))",1
...,...,...,...,...,...,...,...
359,reconvoquer,ʁ Ø k ɔ̃ v O k ɑ̃,"(prs, ptcp)","((segmental, 0, ʁØkɔ̃vOk), (segmental, 3, ɑ̃))",ptcp,"((segmental, 3, ɑ̃))",1
379,sonoriser,s O n O ʁ i z ɑ̃,"(prs, ptcp)","((segmental, 3, ɑ̃), (segmental, 0, sOnOʁiz))",ptcp,"((segmental, 3, ɑ̃))",1
399,sortir,s O ʁ t ɑ̃,"(prs, ptcp)","((segmental, 1, t), (segmental, 4, ɑ̃), (segme...",ptcp,"((segmental, 4, ɑ̃))",1
419,squeezer,s k w i z ɑ̃,"(prs, ptcp)","((segmental, 4, ɑ̃), (segmental, 0, skwiz))",ptcp,"((segmental, 4, ɑ̃))",1
439,touer,t w ɑ̃,"(prs, ptcp)","((segmental, 2, w), (segmental, 4, ɑ̃), (segme...",ptcp,"((segmental, 4, ɑ̃))",1


## Canonical exponence

is the case where there is a 1:1 relation between values and formatives (each value is expressed as a formative). That is to say:

$$|\mathrm{vals}(a)| = 1 \\
    \wedge \\
    |\mathrm{real}(v)| = 1$$

Thus, there are two main ways for non-canonicity to arise, depending on the violation of either statement.

# Typology based on meaning (exp and vals)

## Simple exponence (=canonical meaning)

a formatve, $a$, is said to have a *canonical meaning* (Note: we have also called this in the past *simple exponent*) iff:

$$
|\mathrm{vals}(a)| = 1
$$

A measure of interest here is the size of the *vals* set :

In [10]:
exponents[exponents["|vals|"]==1]

,lexeme,tier,slot,formative,dist,exponence,vals,|vals|,|exp|
1,aller,segmental,0,iʁ,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
7,aller,segmental,2,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
11,apprendre,segmental,1,i,"{(pst, 1sg), (pst, 1pl), (pst, 3pl), (pst, 3sg...",{(pst)},{pst},1,1
22,apprendre,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
33,boire,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
36,croire,segmental,1,y,"{(pst, 1sg), (pst, 1pl), (pst, 3pl), (pst, 3sg...",{(pst)},{pst},1,1
44,croire,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
49,cuire,segmental,2,i,"{(pst, 1sg), (pst, 1pl), (pst, 3pl), (pst, 3sg...",{(pst)},{pst},1,1
54,cuire,segmental,3,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
64,engloutir,segmental,2,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
73,finir,segmental,2,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
82,haïr,segmental,2,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
86,lisser,segmental,1,Ø,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
92,lisser,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
96,manger,segmental,1,Ø,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
102,manger,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
114,moudre,segmental,5,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
120,mourir,segmental,3,i,{(inf)},{(inf)},{inf},1,1
121,mourir,segmental,3,y,"{(pst, 1sg), (pst, 1pl), (pst, 3pl), (pst, 3sg...",{(pst)},{pst},1,1
127,mourir,segmental,5,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
137,partir,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
143,peindre,segmental,3,i,"{(pst, 1sg), (pst, 1pl), (pst, 3pl), (pst, 3sg...",{(pst)},{pst},1,1
148,peindre,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
156,peler,segmental,3,Ø,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
162,peler,segmental,6,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
165,pouvoir,segmental,1,y,"{(pst, 1sg), (pst, 1pl), (pst, 3pl), (pst, 3sg...",{(pst)},{pst},1,1
169,pouvoir,segmental,4,w,{(inf)},{(inf)},{inf},1,1
175,pouvoir,segmental,6,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
177,pouvoir,segmental,6,ʁ,{(inf)},{(inf)},{inf},1,1
181,recevoir,segmental,2,y,"{(pst, 1sg), (pst, 1pl), (pst, 3pl), (pst, 3sg...",{(pst)},{pst},1,1
184,recevoir,segmental,4,wa,{(inf)},{(inf)},{inf},1,1
190,recevoir,segmental,6,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
195,reconvoquer,segmental,1,Ø,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
201,reconvoquer,segmental,3,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
206,sonoriser,segmental,1,Ø,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
212,sonoriser,segmental,3,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
222,sortir,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
226,squeezer,segmental,1,Ø,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
232,squeezer,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1
237,touer,segmental,2,ʁ,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1
242,touer,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1

### Syncretism


A formative $a$ is **syncretic** when it is the exponent of multiple feature-value sets:

$$|\text{exp}(a)| > 1$$

There does not exist a description of 'a', $\delta_a$, which has a cardinality of 1, i.e. one set of features.

In [11]:
exponents[exponents["|exp|"]>1]

,lexeme,tier,slot,formative,dist,exponence,vals,|vals|,|exp|
0,aller,segmental,0,al,"{(prs, ptcp), (prs, 2pl), (pst, 1sg), (pst, 1p...","{(pst), (prs, 1pl), (prs, 2pl)}","{pst, 2pl, 1pl, prs}",4,3
2,aller,segmental,0,v,"{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}","{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}","{2sg, 3pl, 3sg, 1sg, prs}",5,4
3,aller,segmental,1,E,"{(1sg, fut), (2pl, fut), (prs, 1sg), (pst, 1sg...","{(2pl, fut), (1sg), (inf), (pst, 3pl), (prs, 2...","{fut, 3pl, pst, 1sg, prs, 2pl, inf}",7,5
4,aller,segmental,1,a,"{(prs, 3sg), (3sg, fut), (pst, 1pl), (pst, 3sg...","{(3sg), (pst, 1pl), (pst, 2pl), (2sg)}","{2sg, 1pl, 3sg, pst, 2pl}",5,4
8,aller,segmental,2,ɔ̃,"{(fut, 1pl), (3pl, fut), (prs, 3pl), (prs, 1pl)}","{(fut, 1pl), (3pl, fut), (prs, 3pl), (prs, 1pl)}","{prs, 3pl, fut, 1pl}",4,4
...,...,...,...,...,...,...,...,...,...
235,touer,segmental,1,u,"{(prs, 3sg), (3sg, fut), (1sg, fut), (2pl, fut...","{(prs, 3sg), (prs, 1sg), (prs, 3pl), (prs, 2sg...","{fut, 2sg, 3pl, 3sg, 1sg, prs}",6,5
236,touer,segmental,2,w,"{(prs, ptcp), (prs, 2pl), (pst, 1sg), (pst, 1p...","{(pst), (prs, 1pl), (prs, 2pl)}","{pst, 2pl, 1pl, prs}",4,3
238,touer,segmental,3,E,"{(1sg, fut), (2pl, fut), (pst, 1sg), (inf), (p...","{(1sg, fut), (2pl, fut), (pst, 1sg), (inf), (p...","{fut, 3pl, pst, 1sg, prs, 2pl, inf}",7,6
239,touer,segmental,3,a,"{(3sg, fut), (pst, 1pl), (pst, 3sg), (pst, 2pl...","{(3sg, fut), (pst, 1pl), (pst, 3sg), (pst, 2pl...","{fut, 2sg, 1pl, 3sg, pst, 2pl}",6,6
243,touer,segmental,4,ɔ̃,"{(fut, 1pl), (3pl, fut), (prs, 1pl)}","{(fut, 1pl), (3pl, fut), (prs, 1pl)}","{prs, 3pl, fut, 1pl}",4,3

### Cumulative exponence


A formative is **cumulative** when it is the exponent of at least one set of multiple feature-value:

$$\exists x \in \text{exp}(a), |x| > 1$$

In [12]:
#max_dimensions = fr_df["cell"].fillna("").apply(len).max()
# TODO: think about max_dimensions. Thisis computer for an entire dataset
# But some cells invove more dimensions than others (inf vs prs.1sg vs part.prs.f.sg, for example)
# Given a formative, it is more reasonable to ask how cumulative relative to the cell in its dist with the max number of dimensions. -- right ?
# I implemented this, but we can go back, of course.

# ALso, of course this is not very interesting here, as we ony have cells with 1 to 2 dimensions, so it's always 0 or 100%.
sm.classify_cumulation(exponents) #, max_dimensions)
exponents

,lexeme,tier,slot,formative,dist,exponence,vals,|vals|,|exp|,cumulative,cumulative_cells,max_cumulation,maximum_possible_cumulation
0,aller,segmental,0,al,"{(prs, ptcp), (prs, 2pl), (pst, 1sg), (pst, 1p...","{(pst), (prs, 1pl), (prs, 2pl)}","{pst, 2pl, 1pl, prs}",4,3,"{(prs, 1pl), (prs, 2pl)}","{(prs, 1pl), (prs, 2pl)}",2,2
1,aller,segmental,0,iʁ,"{(3sg, fut), (1sg, fut), (2pl, fut), (3pl, fut...",{(fut)},{fut},1,1,{},{},0,2
2,aller,segmental,0,v,"{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}","{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}","{2sg, 3pl, 3sg, 1sg, prs}",5,4,"{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}","{(prs, 1sg), (prs, 3sg), (prs, 3pl), (prs, 2sg)}",2,2
3,aller,segmental,1,E,"{(1sg, fut), (2pl, fut), (prs, 1sg), (pst, 1sg...","{(2pl, fut), (1sg), (inf), (pst, 3pl), (prs, 2...","{fut, 3pl, pst, 1sg, prs, 2pl, inf}",7,5,"{(2pl, fut), (pst, 3pl), (prs, 2pl)}","{(2pl, fut), (pst, 3pl), (prs, 2pl)}",2,2
4,aller,segmental,1,a,"{(prs, 3sg), (3sg, fut), (pst, 1pl), (pst, 3sg...","{(3sg), (pst, 1pl), (pst, 2pl), (2sg)}","{2sg, 1pl, 3sg, pst, 2pl}",5,4,"{(pst, 1pl), (pst, 2pl)}","{(pst, 1pl), (pst, 2pl)}",2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(pst, 1pl)}","{(pst, 1pl)}","{pst, 1pl}",2,1,"{(pst, 1pl)}","{(pst, 1pl)}",2,2
241,touer,segmental,4,t,"{(pst, 2pl)}","{(pst, 2pl)}","{pst, 2pl}",2,1,"{(pst, 2pl)}","{(pst, 2pl)}",2,2
242,touer,segmental,4,ɑ̃,"{(prs, ptcp)}",{(ptcp)},{ptcp},1,1,{},{},0,2
243,touer,segmental,4,ɔ̃,"{(fut, 1pl), (3pl, fut), (prs, 1pl)}","{(fut, 1pl), (3pl, fut), (prs, 1pl)}","{prs, 3pl, fut, 1pl}",4,3,"{(fut, 1pl), (3pl, fut), (prs, 1pl)}","{(fut, 1pl), (3pl, fut), (prs, 1pl)}",2,2
244,touer,segmental,4,ʁ,"{(pst, 3pl)}","{(pst, 3pl)}","{pst, 3pl}",2,1,"{(pst, 3pl)}","{(pst, 3pl)}",2,2

# Typology based on forms (real)

## Unique exponence

a formative, $a$, is said to have a *canonical form* (Note: we have also called this in the past *unique exponence*) iff:

$$
|\mathrm{real}(v)| = 1
$$

In other words, given a lexeme and a value, only a single formative expresses it.

The metric of interest here is the length of the reals

In [13]:
reals[reals["|real|"] == 1]

                                  real  |real|
vals lexeme
1sg  croire        ((segmental, 4, E))       1
     cuire         ((segmental, 3, E))       1
     engloutir     ((segmental, 2, E))       1
     finir         ((segmental, 2, E))       1
     haïr          ((segmental, 2, E))       1
     partir        ((segmental, 4, E))       1
     sortir        ((segmental, 4, E))       1
2sg  croire        ((segmental, 4, a))       1
     cuire         ((segmental, 3, a))       1
     engloutir     ((segmental, 2, a))       1
     finir         ((segmental, 2, a))       1
     haïr          ((segmental, 2, a))       1
     lisser        ((segmental, 3, a))       1
     manger        ((segmental, 3, a))       1
     partir        ((segmental, 4, a))       1
     sortir        ((segmental, 4, a))       1
     squeezer      ((segmental, 3, a))       1
3sg  croire        ((segmental, 4, a))       1
     cuire         ((segmental, 3, a))       1
     engloutir     ((segmental, 2, a))       1
     finir         ((segmental, 2, a))       1
     haïr          ((segmental, 2, a))       1
     lisser        ((segmental, 3, a))       1
     manger        ((segmental, 3, a))       1
     partir        ((segmental, 4, a))       1
     sortir        ((segmental, 4, a))       1
     squeezer      ((segmental, 3, a))       1
inf  aller         ((segmental, 1, E))       1
     cuire         ((segmental, 1, ʁ))       1
     engloutir     ((segmental, 1, ʁ))       1
     finir         ((segmental, 1, ʁ))       1
     haïr          ((segmental, 1, ʁ))       1
     lisser        ((segmental, 1, E))       1
     manger        ((segmental, 1, E))       1
     peler         ((segmental, 3, E))       1
     reconvoquer   ((segmental, 1, E))       1
     sonoriser     ((segmental, 1, E))       1
     squeezer      ((segmental, 1, E))       1
     touer         ((segmental, 3, E))       1
ptcp aller        ((segmental, 2, ɑ̃))       1
     lisser       ((segmental, 4, ɑ̃))       1
     manger       ((segmental, 4, ɑ̃))       1
     mourir       ((segmental, 5, ɑ̃))       1
     partir       ((segmental, 4, ɑ̃))       1
     peler        ((segmental, 6, ɑ̃))       1
     pouvoir      ((segmental, 6, ɑ̃))       1
     recevoir     ((segmental, 6, ɑ̃))       1
     reconvoquer  ((segmental, 3, ɑ̃))       1
     sonoriser    ((segmental, 3, ɑ̃))       1
     sortir       ((segmental, 4, ɑ̃))       1
     squeezer     ((segmental, 4, ɑ̃))       1
     touer        ((segmental, 4, ɑ̃))       1

### Verbose exponence


The **realization of a value in a word** ($\textrm{real}_{\omega}(v)$) as:

$$\textrm{real}_{\omega}(v) = \text{real}(v) \cap \mathrm{wordform}(\omega)$$

**verbose exponence** occurs when in a single word, a value is realized by multiple formatives. For a value $v$ and a word $\omega$:

$$| \textrm{real}_{\omega}(v) | > 1$$

In [14]:
real_w

,lexeme,form,cell,wordform,vals,real_w,|real_w|
3,aller,a l a m,"(pst, 1pl)","((segmental, 2, m), (segmental, 1, a), (segmen...",1pl,"((segmental, 2, m), (segmental, 0, al), (segme...",3
9,aller,i ʁ ɔ̃,"(fut, 1pl)","((segmental, 2, ɔ̃), (segmental, 0, iʁ))",1pl,"((segmental, 2, ɔ̃))",1
15,aller,a l ɔ̃,"(prs, 1pl)","((segmental, 2, ɔ̃), (segmental, 0, al))",1pl,"((segmental, 2, ɔ̃), (segmental, 0, al))",2
23,apprendre,a p ʁ i m,"(pst, 1pl)","((segmental, 1, i), (segmental, 0, apʁ), (segm...",1pl,"((segmental, 4, m))",1
29,apprendre,a p ʁ ɑ̃ d ʁ ɔ̃,"(fut, 1pl)","((segmental, 0, apʁ), (segmental, 3, ʁ), (segm...",1pl,"((segmental, 4, ɔ̃))",1
...,...,...,...,...,...,...,...
359,reconvoquer,ʁ Ø k ɔ̃ v O k ɑ̃,"(prs, ptcp)","((segmental, 0, ʁØkɔ̃vOk), (segmental, 3, ɑ̃))",ptcp,"((segmental, 3, ɑ̃))",1
379,sonoriser,s O n O ʁ i z ɑ̃,"(prs, ptcp)","((segmental, 3, ɑ̃), (segmental, 0, sOnOʁiz))",ptcp,"((segmental, 3, ɑ̃))",1
399,sortir,s O ʁ t ɑ̃,"(prs, ptcp)","((segmental, 1, t), (segmental, 4, ɑ̃), (segme...",ptcp,"((segmental, 4, ɑ̃))",1
419,squeezer,s k w i z ɑ̃,"(prs, ptcp)","((segmental, 4, ɑ̃), (segmental, 0, skwiz))",ptcp,"((segmental, 4, ɑ̃))",1
439,touer,t w ɑ̃,"(prs, ptcp)","((segmental, 2, w), (segmental, 4, ɑ̃), (segme...",ptcp,"((segmental, 4, ɑ̃))",1

In [15]:
real_w[real_w["|real_w|"] > 1]

,lexeme,form,cell,wordform,vals,real_w,|real_w|
3,aller,a l a m,"(pst, 1pl)","((segmental, 2, m), (segmental, 1, a), (segmen...",1pl,"((segmental, 2, m), (segmental, 0, al), (segme...",3
15,aller,a l ɔ̃,"(prs, 1pl)","((segmental, 2, ɔ̃), (segmental, 0, al))",1pl,"((segmental, 2, ɔ̃), (segmental, 0, al))",2
35,apprendre,a p ʁ Ø n ɔ̃,"(prs, 1pl)","((segmental, 3, n), (segmental, 4, ɔ̃), (segme...",1pl,"((segmental, 3, n), (segmental, 2, Ø), (segmen...",3
43,boire,b y m,"(pst, 1pl)","((segmental, 4, m), (segmental, 0, b), (segmen...",1pl,"((segmental, 1, y), (segmental, 4, m))",2
55,boire,b y v ɔ̃,"(prs, 1pl)","((segmental, 4, ɔ̃), (segmental, 0, b), (segme...",1pl,"((segmental, 1, y), (segmental, 3, v), (segmen...",3
...,...,...,...,...,...,...,...
119,engloutir,ɑ̃ g l u t i s ɑ̃,"(prs, ptcp)","((segmental, 0, ɑ̃gluti), (segmental, 1, s), (...",ptcp,"((segmental, 1, s), (segmental, 2, ɑ̃))",2
139,finir,f i n i s ɑ̃,"(prs, ptcp)","((segmental, 0, fini), (segmental, 1, s), (seg...",ptcp,"((segmental, 1, s), (segmental, 2, ɑ̃))",2
159,haïr,a i s ɑ̃,"(prs, ptcp)","((segmental, 0, ai), (segmental, 1, s), (segme...",ptcp,"((segmental, 1, s), (segmental, 2, ɑ̃))",2
219,moudre,m u l ɑ̃,"(prs, ptcp)","((segmental, 1, l), (segmental, 0, mu), (segme...",ptcp,"((segmental, 1, l), (segmental, 5, ɑ̃))",2
279,peindre,p E ɲ ɑ̃,"(prs, ptcp)","((segmental, 0, p), (segmental, 2, Eɲ), (segme...",ptcp,"((segmental, 2, Eɲ), (segmental, 4, ɑ̃))",2

### Allomorphy

There is more than one formative which expresses a given value and these don't co-occur.


**allomorphy** occurs there are more than one way in which $v$ is realized, across words. This could either mean that two or more distinct formatives occur in separate words, or that the value is realized through different *combinations* of a set of formatives, across words.

$$|\{\textrm{real}_{\omega}(v) |  \omega \in \lambda \}| > 1$$

In [16]:
reals = sm.classify_allomorphy(reals, real_w)
reals

                                                               real  |real|  \
vals lexeme
1pl  aller        ((segmental, 2, m), (segmental, 1, a), (segmen...       4
     apprendre    ((segmental, 3, n), (segmental, 4, m), (segmen...       4
     boire        ((segmental, 4, m), (segmental, 4, ɔ̃), (segme...       4
     croire       ((segmental, 4, ɔ̃), (segmental, 3, j), (segme...       3
     cuire        ((segmental, 1, z), (segmental, 3, m), (segmen...       3
...                                                             ...     ...
ptcp reconvoquer                               ((segmental, 3, ɑ̃))       1
     sonoriser                                 ((segmental, 3, ɑ̃))       1
     sortir                                    ((segmental, 4, ɑ̃))       1
     squeezer                                  ((segmental, 4, ɑ̃))       1
     touer                                     ((segmental, 4, ɑ̃))       1

                                                   allomorphic_sets
vals lexeme
1pl  aller        {((segmental, 2, ɔ̃), (segmental, 0, al)), ((s...
     apprendre    {((segmental, 3, n), (segmental, 2, Ø), (segme...
     boire        {((segmental, 4, ɔ̃)), ((segmental, 1, y), (se...
     croire       {((segmental, 4, ɔ̃)), ((segmental, 4, m)), ((...
     cuire        {((segmental, 1, z), (segmental, 3, m)), ((seg...
...                                                             ...
ptcp reconvoquer                             {((segmental, 3, ɑ̃))}
     sonoriser                               {((segmental, 3, ɑ̃))}
     sortir                                  {((segmental, 4, ɑ̃))}
     squeezer                                {((segmental, 4, ɑ̃))}
     touer                                   {((segmental, 4, ɑ̃))}

[242 rows x 3 columns]