# Measuring & Classifying Exponence

**NOTES**:
1. Definitions are still a little ad-hoc but the intuition all works
2. Measures still need need to implemented

A typology of exponence derived in set-theoretic terms making use of setmorph tools

In [1]:
import pandas as pd
%load_ext autoreload
%autoreload 2
import setmorph as sm
import itertools

Data files:

In [2]:
zen_df = sm.read_paradigms("src/setmorph/testdata/sample-zen-out.csv")
ngkolmpu_df = sm.read_paradigms("src/setmorph/testdata/sample-ng-tense-out.csv")
nuer_df = sm.read_paradigms("src/setmorph/testdata/sample-nuer-out.csv")
arabic_df = sm.read_paradigms("src/setmorph/testdata/sample-ar-out.csv")
rus_df = sm.read_paradigms("src/setmorph/testdata/sample-rus-out.csv")
fr_df = sm.read_paradigms("src/setmorph/testdata/sample-fr-out.csv")
uniq_df = sm.read_paradigms("src/setmorph/testdata/unique_test.csv")

Todo: csv tables for features + function to read them. TODO: pruned to a lexeme ? compare a defective lexeme.

In [3]:
fr_features = {
            'Tense': {frozenset({'prs'}), frozenset({'fut'}), frozenset({'pst'})},
            'Mode': {frozenset({'ptcp'}), frozenset({'inf'})},
            'PersonNumber': {frozenset({'1sg'}), frozenset({'2sg'}), frozenset({'3sg'}),
                             frozenset({'1pl'}), frozenset({'2pl'}), frozenset({'3pl'})}
            }

## Delta

Delta is some feature based description of the distribution of a formative, $a$. It is a complete statement describing the cells where $a$ occurs. The total set of deltas for a formative can be considered the maximal knowledge of a speaker about the meaning/distribution of that formative.

- let $a$ be some formative 
- let $x$ be some set of features
- let $y$ be some cell in $\mathrm{dist}(a)$ 
- let $z$ be some cell in $\mathrm{cell}(\lambda)$ 

We can then define $\delta_a$ as
- some set of feature-sets, $\{ x_1, x_2, ... x_n \}$, such that: 

$$
\forall x \in \delta_a, \exists y, z \ (x \subseteq y, z) \\
\forall y, \exists x  \in \delta_a \ (y \supseteq x ) \\
\forall z \supseteq x, \exists y \supseteq x \ (z = y) 
$$

Which means:
1. All sets of features in $\delta_a$ are subsets of at least a cell which is in the distribution of $a$.
2. All cells in the distribution of $a$ are represented by a subset $x$ in $\delta_a$
3. All cells that are supersets of an $x$ in $\delta_a$ are in the distribution of $a$

## Simple exponence

a formatve, $a$, is said to be a *simple exponent* iff:

$$
\exists |\delta_a| = 1 \\
|x \in \delta_a| = 1 
$$

In [4]:
fr_df

     lexeme      cell    form       tier  slot formative     celllist
0     aller   prs.1sg     v E  segmental     0         v   (1sg, prs)
1     aller   prs.1sg     v E  segmental     1         E   (1sg, prs)
2     aller   prs.2sg     v a  segmental     0         v   (prs, 2sg)
3     aller   prs.2sg     v a  segmental     1         a   (prs, 2sg)
4     aller   prs.3sg     v a  segmental     0         v   (3sg, prs)
...     ...       ...     ...        ...   ...       ...          ...
1320  touer       inf   t w E  segmental     2         w        (inf)
1321  touer       inf   t w E  segmental     3         E        (inf)
1322  touer  prs.ptcp  t w ɑ̃  segmental     0         t  (ptcp, prs)
1323  touer  prs.ptcp  t w ɑ̃  segmental     2         w  (ptcp, prs)
1324  touer  prs.ptcp  t w ɑ̃  segmental     4        ɑ̃  (ptcp, prs)

[1325 rows x 7 columns]

We start by computing all exponents relations once and for all:

In [5]:
exponents = sm.find_exponents(fr_df, fr_features)
exponents

,lexeme,tier,slot,formative,exponence,# of cells,dist_a
0,aller,segmental,0,al,"{(2pl, prs), (1pl, prs), (pst)}",10,"{(pst, 2pl), (pst, 2sg), (pst, 3sg), (2pl, prs..."
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 2sg), (fut, 2pl), (fut, 3sg), (fut, 1pl..."
2,aller,segmental,0,v,"{(1sg, prs), (3sg, prs), (prs, 2sg), (3pl, prs)}",4,"{(1sg, prs), (3sg, prs), (prs, 2sg), (3pl, prs)}"
3,aller,segmental,1,E,"{(fut, 2pl), (2pl, prs), (pst, 3pl), (inf), (1...",7,"{(fut, 2pl), (2pl, prs), (1sg, pst), (pst, 3pl..."
4,aller,segmental,1,a,"{(3sg), (pst, 1pl), (pst, 2pl), (2sg)}",8,"{(fut, 2sg), (pst, 2pl), (pst, 2sg), (3sg, prs..."
...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(pst, 1pl)}",1,"{(pst, 1pl)}"
241,touer,segmental,4,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}"
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}"
243,touer,segmental,4,ɔ̃,"{(fut, 3pl), (1pl, prs), (fut, 1pl)}",3,"{(fut, 3pl), (1pl, prs), (fut, 1pl)}"
244,touer,segmental,4,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}"

In [6]:
simple = sm.classify_simple(exponents)
simple

,lexeme,tier,slot,formative,exponence,# of cells,dist_a,simple?
0,aller,segmental,0,al,"{(2pl, prs), (1pl, prs), (pst)}",10,"{(pst, 2pl), (pst, 2sg), (pst, 3sg), (2pl, prs...",no
1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 2sg), (fut, 2pl), (fut, 3sg), (fut, 1pl...",yes
2,aller,segmental,0,v,"{(1sg, prs), (3sg, prs), (prs, 2sg), (3pl, prs)}",4,"{(1sg, prs), (3sg, prs), (prs, 2sg), (3pl, prs)}",no
3,aller,segmental,1,E,"{(fut, 2pl), (2pl, prs), (pst, 3pl), (inf), (1...",7,"{(fut, 2pl), (2pl, prs), (1sg, pst), (pst, 3pl...",no
4,aller,segmental,1,a,"{(3sg), (pst, 1pl), (pst, 2pl), (2sg)}",8,"{(fut, 2sg), (pst, 2pl), (pst, 2sg), (3sg, prs...",no
...,...,...,...,...,...,...,...,...
240,touer,segmental,4,m,"{(pst, 1pl)}",1,"{(pst, 1pl)}",yes
241,touer,segmental,4,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}",yes
242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}",yes
243,touer,segmental,4,ɔ̃,"{(fut, 3pl), (1pl, prs), (fut, 1pl)}",3,"{(fut, 3pl), (1pl, prs), (fut, 1pl)}",no
244,touer,segmental,4,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}",yes

### Syncretism

A formative $a$ is considered to be an example of syncretism iff:

$\neg\exists \delta_a : |\delta_a| = 1$

There does not exist a description of 'a', $\delta_a$, which has a cardinality of 1, i.e. one set of features.

In [7]:
dfsyn = sm.classify_syn(exponents)
dfsyn

,index,lexeme,tier,slot,formative,exponence,# of cells,dist_a,# sets minimally required
0,0,aller,segmental,0,al,"{(2pl, prs), (1pl, prs), (pst)}",10,"{(pst, 2pl), (pst, 2sg), (pst, 3sg), (2pl, prs...",3
1,1,aller,segmental,0,iʁ,{(fut)},6,"{(fut, 2sg), (fut, 2pl), (fut, 3sg), (fut, 1pl...",1
2,2,aller,segmental,0,v,"{(1sg, prs), (3sg, prs), (prs, 2sg), (3pl, prs)}",4,"{(1sg, prs), (3sg, prs), (prs, 2sg), (3pl, prs)}",4
3,3,aller,segmental,1,E,"{(fut, 2pl), (2pl, prs), (pst, 3pl), (inf), (1...",7,"{(fut, 2pl), (2pl, prs), (1sg, pst), (pst, 3pl...",5
4,4,aller,segmental,1,a,"{(3sg), (pst, 1pl), (pst, 2pl), (2sg)}",8,"{(fut, 2sg), (pst, 2pl), (pst, 2sg), (3sg, prs...",4
...,...,...,...,...,...,...,...,...,...
240,240,touer,segmental,4,m,"{(pst, 1pl)}",1,"{(pst, 1pl)}",1
241,241,touer,segmental,4,t,"{(pst, 2pl)}",1,"{(pst, 2pl)}",1
242,242,touer,segmental,4,ɑ̃,{(ptcp)},1,"{(ptcp, prs)}",1
243,243,touer,segmental,4,ɔ̃,"{(fut, 3pl), (1pl, prs), (fut, 1pl)}",3,"{(fut, 3pl), (1pl, prs), (fut, 1pl)}",3
244,244,touer,segmental,4,ʁ,"{(pst, 3pl)}",1,"{(pst, 3pl)}",1

**Measurement**

- Number of cells
- Number of 'sets' in minimal description

To be implemented:
- TODO: Ratio of values over length of a dimension, i.e. 2 cases out of 12 total (harder to do given current implementation.

### Cumulative exponence

A formative $a$ is considered an example of cumulative exponence iff:

$\neg\exists \delta_a : \forall x \in \delta_a, |x| = 1$

There does not exists a $\delta_a$ such that for all sets of features in $\delta_a$ they have a cardinality of 1.

In [8]:
max_dimensions = fr_df["celllist"].fillna("").apply(len).max()
cumulation = sm.classify_cumulation(exponents, max_dimensions)
cumulation

KeyError: 'minimal description'

**Measurement**

- Longest cumulation: how many feature values get cumulated at most
- Longest cumulation / longest possible cumulation
- % cells cumulative - percentage of cells in dist(a) which must be described using cumulation (based on minimal descrition currently)
- % dimensions - length of longest cumulation / longest possible cumulation

## Unique exponence

For a given value, v:
There is only one formative for which its all its deltas must contain that value:

$\exists!a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) $

alternatively:

$| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | = 1$

There exists exactly one $a$ such that all the descriptions of $a$, there exists a set in that description that contains that value.

In [12]:
uniq = sm.classify_unique(exponents)
uniq

NameError: name 'exponents' is not defined


### Verbose exponence

For a given value, v and some word $\omega$:

$$| \{  a \in \mathrm{wordform}(\omega): \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1$ \\
$$

In [13]:
ve = sm.classify_verbose(exponents)
ve[ve.lexeme == "lisser"]

NameError: name 'exponents' is not defined

TODO: This is missing the word itself, can be added by merging with the original df.

**Measurement:**
    
- '# of formatives': number of formatives expressing that valuein a given word

To be implemented / further processing of the above dataframe:
- We could also do an average of formatives expressing a given value
- Number of cells where it is expressed verbose

### Allomorphy

This one is most problematic - still needs tweaking how it fits into the typology, how to measure and define.

There is more than one formative which expresses a given value and these don't co-occur.

For a given value, $v$, we see allomorphy if:

$$
\exists a, b : \forall \delta_a, \delta_b, \exists x \in \delta \ ( v \in x $ )\\
\{\Sigma \in \mathrm{dist}(a)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(b)| v \in \Sigma\} $$

Alternatively:

$$
| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1 \\
\exists a_i,a_j : \{\Sigma \in \mathrm{dist}(a_i)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(a_j)| v \in \Sigma\} 
$$

1. The number of formatives which have $v$ in all their deltas is more than one
2. There exist at least two formative which do not only occur in the same set of cells which contain $v$

In [14]:
allo = sm.classify_allomorphy(ngkolmpu_df)
pd.DataFrame(allo)

/home/sacha/anaconda3/envs/segment/lib/python3.9/site-packages/pandas/core/groupby/generic.py:303: FutureWarning: Dropping invalid columns in SeriesGroupBy.agg is deprecated. In a future version, a TypeError will be raised. Before calling .agg, select only columns which should be valid for the aggregating function.
  results[key] = self.aggregate(func)

TypeError: exponence() missing 1 required positional argument: 'feature_structure'

**Measurement**

- '# of allomorphs'
- '% of allowmorphs to cells containing v' - this can be greater than 100% under current implementation.

Examples:


| (a) SG|  | (b) SG |   | (c) SG |   | (d) SG |
|---|      |---|        |---|        |---|
|x|        | x  |       | x  |       | x  |
|y|        | xy |       | x  |       | x  |
|z|        |  y |       | xy |       | yz |

The current implementation treats the analysis of 'allomorphy of singular' as:

- (a): x, y, z
- (b): x, y
- (c): x, y
- (d): x, yz

Another implementation might consider the following:

- (a): x, y, z
- (b): x, xy, y
- (c): x, xy
- (d): x, yz

## Higher-order exceptionality

See Carroll (2022)