# Measuring & Classifying Exponence

**NOTES**:
1. Definitions are still a little ad-hoc but the intuition all works
2. Measures still need need to implemented

A typology of exponence derived in set-theoretic terms making use of setmorph tools

In [4]:
import pandas as pd
import setmorph as sm
import itertools
from operator import itemgetter

Data files:

In [5]:
zen_df = pd.read_csv("testdata/sample-zen-out.csv")
ngkolmpu_df = pd.read_csv("testdata/sample-ng-tense-out.csv")
nuer_df = pd.read_csv("testdata/sample-nuer-out.csv")
arabic_df = pd.read_csv("testdata/sample-ar-out.csv")
rus_df = pd.read_csv("testdata/sample-rus-out.csv")
fr_df = pd.read_csv("testdata/sample-fr-out.csv")
uniq_df = pd.read_csv("testdata/unique_test.csv")

## Delta

Delta is some feature based description of the distribution of some formative. It is some complete statement describing the cells where a occurs. The total set of delta's for a formative can be considered the maximal knowledge of a speaker about the meaning/distribution of that formative.

let $x$ be some set of features

let $y$ be some cell in $\mathrm{dist}(a)$ 

let $z$ be some cell in $\mathrm{cell}(\lambda)$ 



$ \delta_a = \{ x_1, x_2, ... x_n \} | $ 

$\forall x, \exists y, z (x \subseteq y, z) $

$ \forall y, \exists x (y \supseteq x ) $

$ \forall z \supseteq x, \exists y (z = y) $ (needs to be restricted by x)

## Simple exponence

a formatve, $a$, is said to be a *simple exponent* iff:

$\exists |\delta_a| = 1 $

$|x| = 1 | x \in \delta_a $

In [3]:
simpleout = sm.classify_simple(ngkolmpu_df)
pd.DataFrame(simpleout)

/home/matt/Documents/GitHub/setMorph/src/setmorph/setmorph.py:150: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['celllist'] = parse_cell(df2)

        lexeme       tier  slot formative simple?
0       FOLLOW  segmental     2         i      no
1       FOLLOW  segmental     7        ba     yes
2       FOLLOW  segmental    10         i     yes
3       FOLLOW  segmental     2         u      no
4       FOLLOW  segmental     6         k      no
..         ...        ...   ...       ...     ...
149  FINE_WORK  segmental     4         ə     yes
150  FINE_WORK  segmental     9        ⁿt      no
151  FINE_WORK  segmental     8        ᵑk      no
152  FINE_WORK  segmental     1        ər     yes
153  FINE_WORK  segmental    11        ⁿt      no

[154 rows x 5 columns]

### Syncretism

A formative $a$ is considered to be an example of syncretism iff:

$\neg\exists \delta_a : |\delta_a| = 1$

In [5]:
dfsyn = sm.classify_syn(ngkolmpu_df)
pd.DataFrame(dfsyn)

,lexeme,tier,slot,formative,minimal description,syncretic features,cells,% paradigm
0,WORK,segmental,6,i,"{(dur, hod)}",NaN,NaN,NaN
1,WORK,segmental,2,r,invariant,0.0,11.0,0.818182
2,WORK,segmental,6,ⁿt,"{(dur, fut), (ipfv, rmt)}",2.0,2.0,1.000000
3,WORK,segmental,4,r,"{(fut), (ipfv, rmt)}",2.0,3.0,0.666667
4,WORK,segmental,5,ə,"{(dur, fut)}",NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
150,STALK,segmental,1,w,"{(dur, rct), (ipfv, rmt)}",2.0,2.0,1.000000
151,STALK,segmental,5,k,"{(ipfv), (dur)}",2.0,7.0,0.285714
152,STALK,segmental,9,ᵑk,"{(pfv, rmt)}",NaN,NaN,NaN
153,STALK,segmental,7,ⁿt,"{(ipfv), (rct, pfv), (dur, fut)}",3.0,4.0,0.750000
154,STALK,segmental,6,ə,"{(ipfv), (dur, fut)}",2.0,3.0,0.666667

### Cumulative exponence

A formative $a$ is considered an example of cumulative exponence iff:

$\neg\exists \delta_a : \forall x \in \delta_a, |x| = 1$

In [4]:
dfout = sm.classify_cumulation(ngkolmpu_df)
pd.DataFrame(dfout)

/home/matt/Documents/GitHub/setMorph/src/setmorph/setmorph.py:191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['celllist'] = parse_cell(df2)

,lexeme,tier,slot,formative,cumulative cells,longest cumulation,% of cells cumulative,cumulative values / maximal cumulation
0,WORK,segmental,6,i,0,0,0.0,0.0
1,WORK,segmental,2,r,0,0,0.0,0.0
2,WORK,segmental,6,ⁿt,"[(dur, fut), (ipfv, rmt)]","(dur, fut)",1.0,1.0
3,WORK,segmental,4,r,0,0,0.0,0.0
4,WORK,segmental,5,ə,0,0,0.0,0.0
...,...,...,...,...,...,...,...,...
150,STALK,segmental,1,w,"[(dur, rct), (ipfv, rmt)]","(dur, rct)",1.0,1.0
151,STALK,segmental,5,k,0,0,0.0,0.0
152,STALK,segmental,9,ᵑk,0,0,0.0,0.0
153,STALK,segmental,7,ⁿt,"[(rct, pfv), (dur, fut)]","(rct, pfv)",0.5,1.0
154,STALK,segmental,6,ə,0,0,0.0,0.0

## Unique exponence

For a given value, v:
There is only one formative for which its all its deltas must contain that value:

$\exists!a : \forall x \in \delta_a, v \in x $

In [3]:
uniq = pd.DataFrame(sm.classify_unique(ngkolmpu_df))
uniq

      lexeme value  slot form
0  FINE_WORK   prs     1    y
1      STALK   prs     1    y
2       TELL   hod     5    i
3      EJECT   prs     2    i
4       HIDE   prs     2    i
5    DISROBE   prs     2    i
6       STAB   prs     2    i
7      TOUCH   prs     2    i
8     FOLLOW   prs     2    i

### Allomorphy

There is more than one way to express a given value.

For a given value, $v$, we see allomorphy if:

$ \exists a, b | \forall \delta_a, \delta_b, \exists x ( v \in x $ )$


$ \{\Sigma \in \mathrm{dist}(a)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(b)| v \in \Sigma\} $

In [7]:
allo_ngkolmpu = sm.classify_allomorphy(ngkolmpu_df)

pd.DataFrame(allo_ngkolmpu)

,lexeme,value,# allomorphs,forms
0,TOUCH,pfv,3,"[[(segmental, 1, ə), (segmental, 0, s)], [(seg..."
1,TOUCH,ipfv,5,"[[(segmental, 4, r)], [(segmental, 2, i)], [(s..."
2,TOUCH,rct,4,"[[(segmental, 2, i)], [(segmental, 5, ⁿt)], [(..."
3,TOUCH,dur,5,"[[(segmental, 5, i)], [(segmental, 2, i)], [(s..."
4,TOUCH,rmt,5,"[[(segmental, 5, ᵑk)], [(segmental, 4, r)], [(..."
...,...,...,...,...
58,FOLLOW,ipfv,3,"[[(segmental, 8, ⁿt), (segmental, 6, k), (segm..."
59,FOLLOW,rct,4,"[[(segmental, 2, i)], [(segmental, 8, ⁿt)], [(..."
60,FOLLOW,dur,7,"[[(segmental, 6, k)], [(segmental, 10, i)], [(..."
61,FOLLOW,rmt,3,"[[(segmental, 10, ᵑk)], [(segmental, 2, i), (s..."
62,FOLLOW,fut,2,"[[(segmental, 2, r), (segmental, 1, ə), (segme..."


### Verbose exponence

A given value is realised by two formatives simultaniously.

For a given word, $\omega$, expressing feature value, $v$:

$ \exists a, b | a, b \in W $

$ \forall \delta_a, \delta_b, \exists x ( v \in x $ )

In [4]:
ve_ngkolmpu = sm.classify_ve(ngkolmpu_df)
pd.DataFrame(ve_ngkolmpu)

/home/matt/Documents/GitHub/setMorph/src/setmorph/setmorph.py:67: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['celllist'] = cells

,lexeme,cell,form,form a,delta a,form b,delta b,verbosely expressed value
0,STAB,hod.pfv,s ə l ə ᵑk o l,"(segmental, 0, s)","{(rct, dur), (pfv), (rmt, ipfv), (fut)}","(segmental, 1, ə)","{(pfv), (fut)}",(pfv)
1,STAB,hod.pfv,s ə l ə ᵑk o l,"(segmental, 0, s)","{(rct, dur), (pfv), (rmt, ipfv), (fut)}","(segmental, 1, ə)","{(pfv), (fut)}",(fut)
2,STALK,fut.dur,s ə r ɛ y ɛ r k ə ⁿt,"(segmental, 5, k)","{(ipfv), (dur)}","(segmental, 3, ɛ)","{(ipfv), (dur)}",(ipfv)
3,STALK,fut.dur,s ə r ɛ y ɛ r k ə ⁿt,"(segmental, 5, k)","{(ipfv), (dur)}","(segmental, 3, ɛ)","{(ipfv), (dur)}",(dur)
4,STALK,fut.dur,s ə r ɛ y ɛ r k ə ⁿt,"(segmental, 5, k)","{(ipfv), (dur)}","(segmental, 7, ⁿt)","{(ipfv), (pfv, rct), (fut, dur)}",(ipfv)
...,...,...,...,...,...,...,...,...
1363,TELL,rmt.pfv,s i b ɛ ⁿt ə ᵑk,"(segmental, 0, s)","{(rct, dur), (pfv), (rmt, ipfv), (fut)}","(segmental, 3, ə)","{(ipfv), (pfv, rmt)}",(ipfv)
1364,TELL,rmt.pfv,s i b ɛ ⁿt ə ᵑk,"(segmental, 0, s)","{(rct, dur), (pfv), (rmt, ipfv), (fut)}","(segmental, 3, ə)","{(ipfv), (pfv, rmt)}",(rmt)
1365,HIDE,rct.ipfv,i r o j ə n,"(segmental, 5, jən)","{(rct, ipfv)}","(segmental, 2, i)","{(hod, dur), (prs), (rct, ipfv), (rmt, dur)}","(rct, ipfv)"
1366,HIDE,rmt.dur,i r o u,"(segmental, 5, u)","{(rmt, dur)}","(segmental, 2, i)","{(hod, dur), (prs), (rct, ipfv), (rmt, dur)}",(dur)
1367,HIDE,rmt.dur,i r o u,"(segmental, 5, u)","{(rmt, dur)}","(segmental, 2, i)","{(hod, dur), (prs), (rct, ipfv), (rmt, dur)}","(rmt, dur)"

## Higher-order exceptionality

See Carroll (2022)