# Measuring & Classifying Exponence

**NOTES**:
1. Definitions are still a little ad-hoc but the intuition all works
2. Measures still need need to implemented

A typology of exponence derived in set-theoretic terms making use of setmorph tools

In [1]:
import pandas as pd
import setmorph as sm
import itertools

Data files:

In [2]:
zen_df = pd.read_csv("testdata/sample-zen-out.csv")
ngkolmpu_df = pd.read_csv("testdata/sample-ng-tense-out.csv")
nuer_df = pd.read_csv("testdata/sample-nuer-out.csv")
arabic_df = pd.read_csv("testdata/sample-ar-out.csv")
rus_df = pd.read_csv("testdata/sample-rus-out.csv")
fr_df = pd.read_csv("testdata/sample-fr-out.csv")
uniq_df = pd.read_csv("testdata/unique_test.csv")

## Delta

Delta is some feature based description of the distribution of a formative, $a$. It is a complete statement describing the cells where $a$ occurs. The total set of deltas for a formative can be considered the maximal knowledge of a speaker about the meaning/distribution of that formative.

- let $a$ be some formative 
- let $x$ be some set of features
- let $y$ be some cell in $\mathrm{dist}(a)$ 
- let $z$ be some cell in $\mathrm{cell}(\lambda)$ 

We can then define $\delta_a$ as
- some set of feature-sets, $\{ x_1, x_2, ... x_n \}$, such that: 

$$
\forall x, \exists y, z \ (x \subseteq y, z) \\
\forall y, \exists x \ (y \supseteq x ) \\
\forall z \supseteq x, \exists y \supseteq x \ (z = y) 
$$

## Simple exponence

a formatve, $a$, is said to be a *simple exponent* iff:

$$
\exists |\delta_a| = 1 \\
|x \in \delta_a| = 1 
$$

In [3]:
simpleout = sm.classify_simple(ngkolmpu_df)
pd.DataFrame(simpleout)

/home/matt/Documents/GitHub/setMorph/src/setmorph/setmorph.py:151: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['celllist'] = parse_cell(df2)

      lexeme       tier  slot formative    simple?
0       HIDE  segmental     2         u         no
1       HIDE  segmental     2         i         no
2       HIDE  segmental     3        ro  invariant
3       HIDE  segmental     5         i        yes
4       HIDE  segmental     5         u        yes
..       ...        ...   ...       ...        ...
149  DISROBE  segmental     2         ɛ        yes
150  DISROBE  segmental     7        ᵑk        yes
151  DISROBE  segmental     4        ər         no
152  DISROBE  segmental     7         n        yes
153  DISROBE  segmental     0         s         no

[154 rows x 5 columns]

### Syncretism

A formative $a$ is considered to be an example of syncretism iff:

$\neg\exists \delta_a : |\delta_a| = 1$

There does not exist a description of 'a', $\delta_a$, which has a cardinality of 1, i.e. one set of features.

In [4]:
dfsyn = sm.classify_syn(ngkolmpu_df)
pd.DataFrame(dfsyn)

,lexeme,tier,slot,formative,minimal description,# sets minimally required,# of cells
0,HIDE,segmental,2,u,"{(rct, dur), (ipfv, rmt)}",2.0,2.0
1,HIDE,segmental,2,i,"{(rmt, dur), (rct, ipfv), (prs), (hod, dur)}",4.0,4.0
2,HIDE,segmental,3,ro,invariant,0.0,11.0
3,HIDE,segmental,5,i,"{(hod, dur)}",NaN,NaN
4,HIDE,segmental,5,u,"{(rmt, dur)}",NaN,NaN
...,...,...,...,...,...,...,...
149,DISROBE,segmental,2,ɛ,{(pfv)},NaN,NaN
150,DISROBE,segmental,7,ᵑk,"{(rmt, pfv)}",NaN,NaN
151,DISROBE,segmental,4,ər,"{(ipfv), (dur)}",2.0,7.0
152,DISROBE,segmental,7,n,"{(rct, ipfv)}",NaN,NaN
153,DISROBE,segmental,0,s,"{(pfv), (ipfv, rmt), (rct, dur), (fut)}",4.0,7.0

**Measurement**

- Number of cells
- Number of 'sets' in minimal description

To be implemented:
- Ratio of values over length of a dimension, i.e. 2 cases out of 12 total (harder to do given current implementation.

### Cumulative exponence

A formative $a$ is considered an example of cumulative exponence iff:

$\neg\exists \delta_a : \forall x \in \delta_a, |x| = 1$

There does not exists a $\delta_a$ such that for all sets of features in $\delta_a$ they have a cardinality of 1.

In [5]:
dfout = sm.classify_cumulation(ngkolmpu_df)
pd.DataFrame(dfout)

/home/matt/Documents/GitHub/setMorph/src/setmorph/setmorph.py:192: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['celllist'] = parse_cell(df2)

,lexeme,tier,slot,formative,cumulative cells,longest cumulation,% cells cumulative,% dimensions cumulation
0,HIDE,segmental,2,u,"[(rct, dur), (ipfv, rmt)]",2,100.000000,100.0
1,HIDE,segmental,2,i,"[(rmt, dur), (rct, ipfv), (hod, dur)]",2,75.000000,100.0
2,HIDE,segmental,3,ro,0,0,0.000000,0.0
3,HIDE,segmental,5,i,0,0,0.000000,0.0
4,HIDE,segmental,5,u,0,0,0.000000,0.0
...,...,...,...,...,...,...,...,...
149,DISROBE,segmental,2,ɛ,0,0,0.000000,0.0
150,DISROBE,segmental,7,ᵑk,0,0,0.000000,0.0
151,DISROBE,segmental,4,ər,0,0,0.000000,0.0
152,DISROBE,segmental,7,n,0,0,0.000000,0.0
153,DISROBE,segmental,0,s,"[(ipfv, rmt), (rct, dur)]",2,28.571429,100.0

**Measurement**

- Longest cumulation: how many feature values get cumulated at most
- Longest cumulation / longest possible cumulation
- % cells cumulative - percentage of cells in dist(a) which must be described using cumulation (based on minimal descrition currently)
- % dimensions - length of longest cumulation / longest possible cumulation

## Unique exponence

For a given value, v:
There is only one formative for which its all its deltas must contain that value:

$\exists!a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) $

alternatively:

$| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | = 1$

There exists exactly one $a$ such that all the descriptions of $a$, there exists a set in that description that contains that value.

In [6]:
uniq = pd.DataFrame(sm.classify_unique(ngkolmpu_df))
uniq

      lexeme value  slot form
0       HIDE   prs     2    i
1      STALK   prs     1    y
2       TELL   hod     5    i
3      EJECT   prs     2    i
4      TOUCH   prs     2    i
5     FOLLOW   prs     2    i
6       STAB   prs     2    i
7  FINE_WORK   prs     1    y
8    DISROBE   prs     2    i


### Verbose exponence

For a given value, v and some word $\omega$:

$$| \{  a \in \mathrm{wordform}(\omega): \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1$ \\
$$

In [7]:
ve_ngkolmpu = sm.classify_VE(ngkolmpu_df)
pd.DataFrame(ve_ngkolmpu)

,lexeme,value,word,formatives,# formatives
0,HIDE,hod,"(hod.dur, i r o i)","[(segmental, 2, i), (segmental, 5, i)]",2
1,HIDE,rct,"(rct.dur, s u r o)","[(segmental, 2, u), (segmental, 0, s)]",2
2,HIDE,rct,"(rct.pfv, s ə r o ⁿt)","[(segmental, 5, ⁿt), (segmental, 0, s)]",2
3,HIDE,rct,"(rct.ipfv, i r o j ə n)","[(segmental, 2, i), (segmental, 5, jən)]",2
4,HIDE,ipfv,"(rmt.ipfv, s u r o r ⁿt)","[(segmental, 2, u), (segmental, 4, r), (segmen...",4
...,...,...,...,...,...
184,DISROBE,fut,"(fut.pfv, s ə r ɛ s i p ɛ)","[(segmental, 1, ər), (segmental, 0, s)]",2
185,DISROBE,fut,"(fut.dur, s ə r s i p ə r ⁿt)","[(segmental, 7, ⁿt), (segmental, 1, ər), (segm...",3
186,DISROBE,rmt,"(rmt.pfv, s ɛ s i p ɛ ᵑk)","[(segmental, 7, ᵑk), (segmental, 0, s)]",2
187,DISROBE,rmt,"(rmt.dur, i s i p ə r u)","[(segmental, 7, u), (segmental, 2, i)]",2
188,DISROBE,rmt,"(rmt.ipfv, s u s i p ə r ə r ⁿt)","[(segmental, 2, u), (segmental, 6, r), (segmen...",4

**Measurement:**
    
- '# of formatives': number of formatives expressing that valuein a given word

To be implemented / further processing of the above dataframe:
- We could also do an average of formatives expressing a given value
- Number of cells where it is expressed verbose

### Allomorphy

This one is most problematic - still needs tweaking how it fits into the typology, how to measure and define.

There is more than one formative which expresses a given value and these don't co-occur.

For a given value, $v$, we see allomorphy if:

$$
\exists a, b : \forall \delta_a, \delta_b, \exists x \in \delta \ ( v \in x $ )\\
\{\Sigma \in \mathrm{dist}(a)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(b)| v \in \Sigma\} $$

Alternatively:

$$
| \{  a : \forall \delta_a, \exists x \in \delta_a \ (v \in x) \} | > 1 \\
\exists a_i,a_j : \{\Sigma \in \mathrm{dist}(a_i)| v \in \Sigma\} \neq \{\Sigma \in \mathrm{dist}(a_j)| v \in \Sigma\} 
$$

1. The number of formatives which have $v$ in all their deltas is more than one
2. There exist at least two formative which do not only occur in the same set of cells which contain $v$

In [8]:
allo = sm.classify_allomorphy(ngkolmpu_df)
pd.DataFrame(allo)

,lexeme,value,# allomorphs,% of allomorphs to cells containing v,forms
0,HIDE,rct,5,166.666667,"[[(segmental, 2, u)], [(segmental, 2, i)], [(s..."
1,HIDE,ipfv,5,250.000000,"[[(segmental, 2, u)], [(segmental, 2, i)], [(s..."
2,HIDE,dur,6,120.000000,"[[(segmental, 2, u)], [(segmental, 2, i)], [(s..."
3,HIDE,pfv,3,75.000000,"[[(segmental, 2, ə), (segmental, 0, s)], [(seg..."
4,HIDE,fut,2,100.000000,"[[(segmental, 2, ə), (segmental, 1, ər), (segm..."
...,...,...,...,...,...
58,DISROBE,ipfv,6,300.000000,"[[(segmental, 5, ə), (segmental, 4, ər)], [(se..."
59,DISROBE,dur,7,140.000000,"[[(segmental, 4, ər)], [(segmental, 7, u)], [(..."
60,DISROBE,pfv,3,75.000000,"[[(segmental, 6, ɛ), (segmental, 2, ɛ), (segme..."
61,DISROBE,fut,2,100.000000,"[[(segmental, 1, ər), (segmental, 0, s)], [(se..."
62,DISROBE,rmt,6,200.000000,"[[(segmental, 7, u)], [(segmental, 2, u)], [(s..."

**Measurement**

- '# of allomorphs'
- '% of allowmorphs to cells containing v' - this can be greater than 100% under current implementation.

Examples:

| (a) SG|  | (b) SG |   | (c) SG |   | (d) SG | 
|---|      |---|        |---|        |---|
|x|        | x  |       | x  |       | x  |
|y|        | xy |       | x  |       | x  |
|z|        |  y |       | xy |       | yz |

The current implementation treats the analysis of 'allomorphy of singular' as:

- (a): x, y, z
- (b): x, y
- (c): x, y
- (d): x, yz

Another implementation might consider the following:

- (a): x, y, z
- (b): x, xy, y
- (c): x, xy
- (d): x, yz

## Higher-order exceptionality

See Carroll (2022)